"""Rebuild PCM masters and compact runtime bank from preserved CC0 sources. Requires ffmpeg."""
import pathlib, subprocess, shutil, json, hashlib, math, random, wave, struct
ROOT=pathlib.Path(__file__).resolve().parents[3]
HERE=pathlib.Path(__file__).resolve().parent
OUT=ROOT/'game/audio/effects'
OUT.mkdir(parents=True,exist_ok=True)
recipes={
'focus':('interface','tick_001',.12),'confirm':('interface','confirmation_002',.28),'cancel':('interface','back_001',.22),
'contact-metal':('impact','impactMetal_light_000',.22),'contact-wood':('impact','impactWood_light_000',.22),
'contact-glass':('impact','impactGlass_light_000',.28),'contact-soft':('impact','impactSoft_medium_000',.22),
'gate':('scifi','doorOpen_001',.6),'impact':('impact','impactPunch_medium_000',.26),
'paper':('interface','scratch_001',.25),'deploy':('scifi','forceField_001',.45),
'attack':('scifi','laserSmall_001',.3),'interference':('scifi','computerNoise_001',.35),
'erosion':('scifi','impactMetal_001',.36),'switch':('interface','switch_002',.22),
'pickup':('interface','maximize_002',.4),'closure':('interface','pluck_001',.18),
}
for material in ['metal','wood','glass','soft']:
    pack,source,duration=recipes['contact-'+material]
    for variation in [1,2]:
        recipes[f'contact-{material}-{variation}']=(pack,source[:-3]+f'{variation:03d}',duration)
bank={}
for name,(pack,source,duration) in recipes.items():
    original=HERE/'originals'/pack/(source+'.ogg')
    if not original.exists():
        original.parent.mkdir(parents=True,exist_ok=True)
        shutil.copy2(ROOT/'.cache/audio-sources'/pack/'Audio'/(source+'.ogg'),original)
        shutil.copy2(ROOT/'.cache/audio-sources'/pack/'License.txt',original.parent/'License.txt')
    dest=OUT/(name+'.wav')
    filters=f'atrim=0:{duration},asetpts=PTS-STARTPTS,highpass=f=65,lowpass=f=9500,afade=t=in:d=0.004,afade=t=out:st={max(.005,duration-.04)}:d=0.04,alimiter=limit=0.65:level=false'
    subprocess.run(['ffmpeg','-v','error','-y','-i',str(original),'-af',filters,'-ar','32000','-ac','1','-c:a','pcm_s16le',str(dest)],check=True)
    bank[name]={'file':dest.name,'loop':False}
# Periodic harmonics avoid arbitrary loop cuts. Seeded noise has an overlapping
# periodic envelope. Every source is original; no melody is copied from music.
for name in ['motor','rotor','wings','wheels','grain','flow','warning','start','retry','loss','respawn','win','reveal-small','reveal-medium','reveal-large','neutralized','reactivated']:
    loop=name in ['motor','rotor','wings','wheels','grain','flow']
    duration=1 if loop else {'win':1.35,'loss':.6,'warning':.42,'reveal-small':.2,'reveal-medium':.4,'reveal-large':.65}.get(name,.45)
    sr=32000;n=int(duration*sr); rng=random.Random(724); data=[]; smooth=0
    for i in range(n):
        t=i/sr;u=i/n
        env=1 if loop else min(1,t/.008)*max(0,1-u)**1.7
        smooth=.87*smooth+.13*rng.uniform(-1,1)
        if loop:
            freq={'motor':90,'rotor':65,'wheels':46,'grain':170,'flow':210,'wings':36}[name]
            pulse=.6+.4*math.sin(2*math.pi*(5 if name=='wings' else 13)*t)
            value=(math.sin(2*math.pi*freq*t)+.24*math.sin(2*math.pi*freq*3*t))*.065*pulse
            if name in ['grain','flow','wings']: value+=smooth*.17*math.sin(math.pi*u)**2
        else:
            intervals={'start':[0,7,12], 'retry':[7,2,9], 'respawn':[0,12,7,16], 'warning':[1,1], 'loss':[7,3,0,-12], 'win':[0,4,7,12,16,19], 'neutralized':[7,12], 'reactivated':[12,1], 'reveal-small':[0,7], 'reveal-medium':[0,4,12], 'reveal-large':[0,4,7,12,16]}[name]
            value=0
            for j,step in enumerate(intervals):
                onset=j*duration/(len(intervals)+1); dt=t-onset
                if dt>=0:
                    f=({'warning':620,'loss':260,'reactivated':520}.get(name,440))*2**(step/12)
                    value+=(math.sin(2*math.pi*f*dt)+.2*math.sin(2*math.pi*f*(2.37 if name=='warning' else 2.01)*dt))*math.exp(-dt*(17 if name=='warning' else 12))*min(1,dt/.004)*.095
            value+=smooth*.045*math.exp(-t*16)
        data.append(max(-.8,min(.8,value*env)))
    dest=OUT/(name+'.wav')
    with wave.open(str(dest),'wb') as w:
        w.setparams((1,2,sr,n,'NONE','not compressed'));w.writeframes(struct.pack('<'+'h'*n,*[int(v*32767) for v in data]))
    bank[name]={'file':dest.name,'loop':loop}
for name,entry in bank.items():
    file=OUT/entry['file'];entry['bytes']=file.stat().st_size;entry['sha256']=hashlib.sha256(file.read_bytes()).hexdigest()
    master=HERE/'masters'/file.name;master.parent.mkdir(exist_ok=True);shutil.copy2(file,master)
(OUT/'bank.mjs').write_text('// Generated by authoring/audio/revealline-v1/produce.py.\nexport const EFFECT_BANK = '+json.dumps(bank,indent=2)+';\n')
(HERE/'recipes.json').write_text(json.dumps(recipes,indent=2)+'\n')
print('Bank:',len(bank),'assets,',sum(v['bytes'] for v in bank.values()),'bytes')
