import { getLocale } from '../i18n/index.mjs';
const copy = {
  en: {
    lessons: 'Hunt lessons · six missions',
    variant: 'Encounter variant',
    authored: 'As designed',
    off: 'No optional encounters',
    patrol: 'Patrol encounters',
    bonus: 'Bonus hunt',
    'capture-quota': 'Capture + hunt',
    hunt: 'Hunt only',
    variantHelp: 'Applies to a new attempt. Continue and Retry keep the accepted enemies and goal.',
    unavailable: 'This variant is not available for this mission.',
    brutal: 'Brutal enemy destruction — blood, body parts and explosions',
    blood: 'Blood and body parts',
    brutalHelp:
      'Optional graphic pixel destruction. Hunting also works with this off. Reduced effects limits motion.',
    preview: 'Preview destruction',
    saving: 'This choice is active for this session; saving is unavailable.',
    retry: 'Retry saving',
    targets: 'Hunt targets',
    score: 'Hunt score',
    touch: 'Contact',
    enclosed: 'Enclosed',
    remaining: 'Remaining',
    best: 'Best hunt',
    bonusGoal: 'Capture the picture. Hunt humanoids for a separate bonus score.',
    quotaGoal: 'Complete the capture goal and the hunt quota.',
    huntGoal: 'Eliminate every humanoid target. Capture and contact both count.',
    hint: 'Touch humanoids to defeat them. Guards shoot at exposed players. Ordinary keepers remain dangerous.',
    all: 'All targets',
    contactMastery: 'All by contact',
    clean: 'No damage',
    runner: 'Runner',
    guard: 'Guard',
  },
  uk: {
    lessons: 'Уроки полювання · шість місій',
    variant: 'Варіант сутичок',
    authored: 'За задумом',
    off: 'Без додаткових ворогів',
    patrol: 'Патрульні сутички',
    bonus: 'Бонусне полювання',
    'capture-quota': 'Захоплення + полювання',
    hunt: 'Лише полювання',
    variantHelp:
      'Застосовується до нової спроби. Продовження та повтор зберігають прийнятих ворогів і мету.',
    unavailable: 'Цей варіант недоступний для цієї місії.',
    brutal: 'Жорстоке знищення ворогів — кров, частини тіл і вибухи',
    blood: 'Кров і частини тіл',
    brutalHelp:
      'Необов’язкові відверті піксельні ефекти. Полювання працює й без них. Зменшені ефекти обмежують рух.',
    preview: 'Переглянути знищення',
    saving: 'Вибір діє протягом цього сеансу; збереження недоступне.',
    retry: 'Повторити збереження',
    targets: 'Цілі полювання',
    score: 'Бали полювання',
    touch: 'Дотик',
    enclosed: 'Захоплено',
    remaining: 'Залишилося',
    best: 'Рекорд полювання',
    bonusGoal: 'Відкрийте зображення. Полюйте на гуманоїдів заради окремих бонусних балів.',
    quotaGoal: 'Досягніть мети захоплення та квоти полювання.',
    huntGoal: 'Знищте всіх гуманоїдів. Дотик і захоплення зараховуються.',
    hint: 'Торкніться гуманоїда, щоб знищити його. Охоронці стріляють у незахищених гравців. Звичайні вороги залишаються небезпечними.',
    all: 'Усі цілі',
    contactMastery: 'Усі дотиком',
    clean: 'Без пошкоджень',
    runner: 'Утікач',
    guard: 'Охоронець',
  },
};
export const huntText = (key, locale = getLocale()) =>
  (copy[locale] ?? copy.en)[key] ?? copy.en[key] ?? key;
