import { PRACTICE_FORMAT, PRACTICE_MODEL } from './model.mjs';

const checkpoint = (x, z, altitude = 100, extras = {}) => ({
  x,
  z,
  altitude,
  radius: 75,
  verticalTolerance: 15,
  heading: null,
  headingTolerance: 10,
  holdTicks: 8,
  landed: false,
  ...extras,
});
const landing = (x = 1000, z = 1600) =>
  checkpoint(x, z, 0, { radius: 60, verticalTolerance: 5, holdTicks: 20, landed: true });
const lift = (x = 1000, z = 1600) => checkpoint(x, z, 100, { holdTicks: 20 });
const drill = (
  id,
  title,
  ukTitle,
  brief,
  ukBrief,
  discovery,
  ukDiscovery,
  checkpoints,
  spawn = { x: 1000, z: 1600, altitude: 0, heading: 0 },
) => ({
  id,
  revision: 'v1',
  locales: {
    en: { title, brief, discovery },
    uk: { title: ukTitle, brief: ukBrief, discovery: ukDiscovery },
  },
  spawn,
  checkpoints: checkpoints.map((point, index) => ({ id: `point-${index + 1}`, ...point })),
});

export const CIVILIAN_PRACTICE_CATALOGUE = {
  format: PRACTICE_FORMAT,
  id: 'civilian-gym',
  revision: 'v1',
  scenario: 'civilian-gym',
  model: PRACTICE_MODEL,
  locales: {
    en: {
      title: 'Civilian flight gym',
      description:
        'Twelve optional assisted practice drills in a fictional empty gym. Explore direction, orientation, altitude and controlled returns.',
    },
    uk: {
      title: 'Цивільний тренувальний зал',
      description:
        'Дванадцять необов’язкових вправ зі спрощеним керуванням у вигаданому порожньому залі. Досліджуйте напрямок, орієнтацію, висоту та контрольоване повернення.',
    },
  },
  world: { width: 2000, depth: 2000, ceiling: 300 },
  drills: [
    drill(
      'lift-and-land',
      'Lift and return',
      'Підйом і повернення',
      'Rise into the first ring, settle there, then return to the landing pad.',
      'Підніміться в перше кільце, зупиніться в ньому й поверніться на посадковий майданчик.',
      'Small commands make approaching a target easier in this assisted model.',
      'У цій спрощеній моделі невеликі команди полегшують наближення до цілі.',
      [lift(), landing()],
    ),
    drill(
      'steady-hover',
      'A steady point',
      'Стабільна точка',
      'Stay in the target volume for three seconds, then land.',
      'Утримуйтеся в цільовому об’ємі три секунди, потім приземліться.',
      'Neutral holds position here because assistance is built into this model; it is not a promise about real flight modes.',
      'Нейтраль утримує положення тут завдяки допомозі моделі; це не правило для справжніх режимів польоту.',
      [
        checkpoint(1000, 1600, 100, { radius: 40, verticalTolerance: 10, holdTicks: 60 }),
        landing(),
      ],
    ),
    drill(
      'forward-return',
      'Forward and back',
      'Уперед і назад',
      'Visit two forward markers and return with the same heading.',
      'Відвідайте дві мітки попереду й поверніться з тим самим курсом.',
      'Pitch commands are relative to the nose, not the top of the screen.',
      'Команди тангажу відносні до носа, а не до верхнього краю екрана.',
      [lift(), checkpoint(1000, 1000), checkpoint(1000, 500), checkpoint(1000, 1600), landing()],
    ),
    drill(
      'sideways',
      'Across the mat',
      'Уздовж килимка',
      'Move left, right and back to the centre without turning the nose.',
      'Перемістіться ліворуч, праворуч і назад до центру, не повертаючи ніс.',
      'Roll and yaw have different jobs: lateral movement and nose direction.',
      'Крен і рискання мають різні ролі: боковий рух та напрямок носа.',
      [lift(), checkpoint(500, 1300), checkpoint(1500, 1300), checkpoint(1000, 1600), landing()],
    ),
    drill(
      'square',
      'Four corners',
      'Чотири кути',
      'Trace the four corners of a square, then land.',
      'Пройдіть чотири кути квадрата й приземліться.',
      'A sequence is complete only after its checkpoints have been reached in order.',
      'Послідовність завершена лише після проходження всіх контрольних точок у заданому порядку.',
      [
        lift(),
        checkpoint(500, 1500),
        checkpoint(500, 500),
        checkpoint(1500, 500),
        checkpoint(1500, 1500),
        landing(),
      ],
    ),
    drill(
      'compass-turns',
      'Turn the compass',
      'Поверніть компас',
      'Hold the centre while facing east, south, west and north.',
      'Утримуйте центр, спрямовуючи ніс на схід, південь, захід і північ.',
      'Yaw changes heading; it does not itself move the aircraft across the floor.',
      'Рискання змінює курс; саме по собі воно не переміщує апарат по підлозі.',
      [
        lift(),
        ...[90, 180, 270, 0].map((heading) =>
          checkpoint(1000, 1600, 100, { heading, holdTicks: 12 }),
        ),
        landing(),
      ],
    ),
    drill(
      'turn-and-travel',
      'Turn, then travel',
      'Поворот, потім рух',
      'Face each highlighted heading before travelling to its marker.',
      'Поверніться на позначений курс перед рухом до відповідної мітки.',
      'After a turn, the same forward command points in a different world direction.',
      'Після повороту та сама команда вперед спрямована в інший бік світу.',
      [
        lift(),
        checkpoint(1500, 1600, 100, { heading: 90 }),
        checkpoint(1500, 700, 100, { heading: 0 }),
        checkpoint(500, 700, 100, { heading: 270 }),
        landing(),
      ],
    ),
    drill(
      'altitude-ladder',
      'Height ladder',
      'Драбина висоти',
      'Visit four height bands over the same floor marker.',
      'Відвідайте чотири діапазони висоти над тією самою міткою підлоги.',
      'The side gauge matters: a correct floor position can still be too high or too low.',
      'Бічна шкала важлива: над правильною точкою підлоги можна бути надто високо або низько.',
      [60, 160, 240, 100]
        .map((height) => checkpoint(1000, 1600, height, { verticalTolerance: 8, holdTicks: 20 }))
        .concat(landing()),
    ),
    drill(
      'slalom',
      'Open gate slalom',
      'Слалом крізь відкриті ворота',
      'Pass the alternating target rings, keeping the height band.',
      'Пройдіть кільця, що чергуються, утримуючи діапазон висоти.',
      'Looking at the next target helps you plan an approach before changing direction.',
      'Погляд на наступну ціль допомагає спланувати наближення до зміни напрямку.',
      [
        lift(),
        checkpoint(650, 1300),
        checkpoint(1350, 1050),
        checkpoint(650, 800),
        checkpoint(1350, 550),
        landing(),
      ],
    ),
    drill(
      'figure-eight',
      'A gentle figure eight',
      'Плавна вісімка',
      'Follow both loops in the shown order and return to the pad.',
      'Пройдіть обидві петлі в показаному порядку й поверніться на майданчик.',
      'A figure eight combines repeated direction changes with a shared crossing.',
      'Вісімка поєднує повторні зміни напрямку зі спільним перетином.',
      [
        lift(),
        ...[
          [1000, 1000],
          [1300, 700],
          [1600, 1000],
          [1300, 1300],
          [1000, 1000],
          [700, 700],
          [400, 1000],
          [700, 1300],
          [1000, 1000],
        ].map(([x, z]) => checkpoint(x, z)),
        landing(),
      ],
    ),
    drill(
      'two-landings',
      'Two quiet landings',
      'Дві спокійні посадки',
      'Settle onto each small pad with no planar command held.',
      'Спокійно сядьте на кожен малий майданчик без утримання команди горизонтального руху.',
      'Landing needs both a low height and a settled position; touching the floor elsewhere is not completion.',
      'Для посадки потрібні мала висота й стабільне положення; дотик до підлоги в іншому місці не завершує вправу.',
      [
        lift(),
        checkpoint(600, 800),
        { ...landing(600, 800), radius: 35 },
        lift(600, 800),
        checkpoint(1400, 800),
        { ...landing(1400, 800), radius: 35 },
      ],
    ),
    drill(
      'gym-tour',
      'The complete gym tour',
      'Повний маршрут залом',
      'Combine direction changes, height bands, headings and a final landing.',
      'Поєднайте зміни напрямку, діапазони висоти, курси та завершальну посадку.',
      'This completes a simplified practice route, not a qualification to fly a real aircraft.',
      'Це завершення спрощеного тренувального маршруту, а не підтвердження кваліфікації для справжнього польоту.',
      [
        lift(),
        checkpoint(500, 1300, 100, { heading: 270 }),
        checkpoint(500, 500, 180, { heading: 0 }),
        checkpoint(1500, 500, 180, { heading: 90 }),
        checkpoint(1500, 1300, 60, { heading: 180 }),
        checkpoint(1000, 1600, 100, { heading: 0 }),
        landing(),
      ],
    ),
  ],
};
