export const PRACTICE_COPY = {
  en: {
    title: 'Civilian flight gym',
    drill: 'Practice drill',
    prepare: 'Prepare flight',
    backToGame: 'Back to game',
    start: 'Start / resume',
    pause: 'Pause',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    reset: 'Reset drill',
    controls: 'Controls & authoring',
    connect: 'Use standard gamepad',
    offline: 'Prepare this package offline',
    removeOffline: 'Remove this package offline',
    instructions:
      'WASD / arrows: forward, back and sideways. Q/E: yaw left/right. R/F: rise/descend. Space/Escape: pause. Touch: hold the labelled buttons. Keyboard movement belongs to the focused gym. Release controls before resuming.',
    limitation:
      'Assisted kinematic model: commands select movement and climb rate; neutral holds position. No inertia, aerodynamics, real throttle curve, radio configuration or aircraft connection. Completing these fictional gym drills does not demonstrate real flight proficiency.',
    mode: 'Standard gamepad, illustrative Mode 2: left stick yaw/climb; right stick roll/pitch. Centre all sticks and release buttons after connecting or pausing. Menu / east button pauses. Other controller mappings fall back to keyboard and touch.',
    target: 'Next checkpoint',
    position: 'Position',
    height: 'Height',
    heading: 'Heading',
    complete: 'Practice route complete',
    ready: 'Ready',
    active: 'Practising',
    paused: 'Paused — resume explicitly',
    progress: 'Checkpoints',
    hold: 'Settle in the target',
    land: 'Land with no sideways or forward command',
    pitch: 'Forward',
    back: 'Back',
    left: 'Left',
    right: 'Right',
    yawLeft: 'Nose left',
    yawRight: 'Nose right',
    up: 'Rise',
    down: 'Descend',
    close: 'Back to gym',
    static: 'Reduced effects',
    author: 'Drill catalogue JSON',
    export: 'Prepare catalogue JSON',
    import: 'Validate and preview catalogue',
    invalid: 'Catalogue was rejected; the current drill is unchanged.',
    imported: 'Catalogue loaded. Practice was reset; existing game progress is untouched.',
    exportTrace: 'Prepare current transcript',
    traceReady: 'Transcript prepared. It records practice inputs, not a Journey reward.',
    unavailable: 'No standard gamepad available. Keyboard and touch remain available.',
    center: 'Gamepad selected. Centre sticks and release every button.',
    connected: 'Gamepad ready.',
    disconnected: 'Gamepad unavailable; practice paused. Resume with keyboard or touch.',
    installed: 'This exact optional package is ready offline.',
    installFailed: 'Offline preparation failed. Online practice remains available.',
    removed: 'Only this optional package cache was removed.',
    fallback:
      'Canvas is unavailable. Position, height and checkpoint text remain usable with the same controls.',
    kept: 'Practice completions shown here belong only to this visit.',
    noTimer: 'No countdown · ordered targets · session-only practice results',
    sessionFull: 'This practice recording is full. Reset the drill to begin a fresh attempt.',
    arena: 'Civilian training gym',
    touch: 'Touch and single-step controls',
    json: 'Practice catalogue or transcript JSON',
    source: 'Model limits and authoring guide',
  },
  uk: {
    title: 'Цивільний тренувальний зал',
    drill: 'Тренувальна вправа',
    prepare: 'Підготувати політ',
    backToGame: 'До гри',
    start: 'Почати / продовжити',
    pause: 'Пауза',
    soundOn: 'Звук увімкнено',
    soundOff: 'Звук вимкнено',
    reset: 'Скинути вправу',
    controls: 'Керування й редагування',
    connect: 'Використати стандартний геймпад',
    offline: 'Підготувати цей пакет офлайн',
    removeOffline: 'Видалити цей пакет офлайн',
    instructions:
      'WASD / стрілки: уперед, назад і вбік. Q/E: рискання ліворуч/праворуч. R/F: підйом/спуск. Пробіл/Escape: пауза. Дотик: утримуйте підписані кнопки. Клавіатура керує залом, коли він у фокусі. Відпустіть органи керування перед продовженням.',
    limitation:
      'Спрощена кінематична модель з допомогою: команди задають рух і швидкість зміни висоти; нейтраль утримує положення. Немає інерції, аеродинаміки, справжньої кривої газу, налаштування радіо або зв’язку з апаратом. Завершення вправ у вигаданому залі не підтверджує навичок справжнього польоту.',
    mode: 'Стандартний геймпад, ілюстративний Mode 2: лівий стик — рискання/висота; правий — крен/тангаж. Центруйте стики й відпустіть кнопки після під’єднання або паузи. Menu / східна кнопка ставить на паузу. Для інших схем доступні клавіатура й дотик.',
    target: 'Наступна контрольна точка',
    position: 'Положення',
    height: 'Висота',
    heading: 'Курс',
    complete: 'Тренувальний маршрут завершено',
    ready: 'Готово',
    active: 'Тренування',
    paused: 'Пауза — продовжіть явно',
    progress: 'Контрольні точки',
    hold: 'Зупиніться в цілі',
    land: 'Сядьте без команди руху вперед або вбік',
    pitch: 'Уперед',
    back: 'Назад',
    left: 'Ліворуч',
    right: 'Праворуч',
    yawLeft: 'Ніс ліворуч',
    yawRight: 'Ніс праворуч',
    up: 'Підйом',
    down: 'Спуск',
    close: 'Назад до залу',
    static: 'Менше ефектів',
    author: 'JSON каталогу вправ',
    export: 'Підготувати JSON каталогу',
    import: 'Перевірити й переглянути каталог',
    invalid: 'Каталог відхилено; поточна вправа не змінилася.',
    imported: 'Каталог завантажено. Тренування скинуто; прогрес основної гри не змінено.',
    exportTrace: 'Підготувати поточний запис',
    traceReady: 'Запис підготовлено. Він містить команди тренування, а не нагороду Journey.',
    unavailable: 'Стандартного геймпада немає. Клавіатура й дотик залишаються доступними.',
    center: 'Геймпад вибрано. Центруйте стики й відпустіть усі кнопки.',
    connected: 'Геймпад готовий.',
    disconnected:
      'Геймпад недоступний; тренування призупинено. Продовжіть клавіатурою або дотиком.',
    installed: 'Цей точний додатковий пакет готовий офлайн.',
    installFailed: 'Не вдалося підготувати офлайн. Онлайн-тренування доступне.',
    removed: 'Видалено лише кеш цього додаткового пакета.',
    fallback:
      'Canvas недоступний. Текст положення, висоти й контрольної точки доступний із тим самим керуванням.',
    kept: 'Показані завершення вправ належать лише цьому відвідуванню.',
    noTimer: 'Без зворотного відліку · послідовні цілі · результати лише в сеансі',
    sessionFull: 'Запис цього тренування заповнено. Скиньте вправу, щоб почати нову спробу.',
    arena: 'Цивільний тренувальний зал',
    touch: 'Сенсорне та покрокове керування',
    json: 'JSON каталогу вправ або запису тренування',
    source: 'Обмеження моделі та посібник автора',
  },
};
