import * as fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { loadAuthority, sha, isTransient } from './audit-main.mjs';
import { BASE, expectedTypes } from './http-engine.mjs';
const home=path.dirname(fileURLToPath(import.meta.url)),primary=path.resolve(home,'../../..'),out=path.join(home,'runs/main2b8521-complete-1');
const bindingFile=path.join(home,'inputs/2b8521b0a118df8663f93de5500e14da11741407/binding.json'),bindingSha='ac63f868131ff7e54065cb6b9654cfedd2b9c737e60181322e9bc82cc8923a24';
const files=[];
async function read(file){const stat=await fs.lstat(file);assert(stat.isFile()&&!stat.isSymbolicLink()&&stat.size<16000000);const raw=await fs.readFile(file);files.push({path:path.relative(primary,file),bytes:raw.length,sha256:sha(raw)});return raw;}
assert.equal(sha(await read(path.join(home,'audit-main.mjs'))),'70b628c4e2b68fa5c9fe3999cbe39db8f9a07e29191dcb261cba280862d9193c');
assert.equal(sha(await read(path.join(home,'http-engine.mjs'))),'7660dd3ac7453bc31f6ba26e005340dd719986ac7fc1a29bd42b30db71b81c6d');
const a=await loadAuthority(bindingFile,bindingSha);assert.equal(a.models.receipt.publishable,true);assert.equal(a.models.receipt.browserAdmissionsRequired,true);assert.deepEqual(a.testingVersions,[]);
for(const pin of a.reads) assert.equal(sha(await read(pin.file)),pin.sha256);
const report=JSON.parse(await read(path.join(out,'report.json')));
for(const name of ['controllerCommit','controllerTree','gameSourceRevision','qualifiedSourceTree','runId','deploymentId','currentVersion'])assert.deepEqual(report[name],a.binding[name]);
assert.equal(report.controllerCommit,'2b8521b0a118df8663f93de5500e14da11741407');assert.equal(report.controllerTree,'5dcd633d3cb1ba69e7a66fe5d2074239c9b33071');assert.equal(report.bindingSha256,bindingSha);assert.equal(report.artifactReceiptSha256,a.binding.pins.receipt.sha256);assert.equal(report.expectedInventorySha256,a.binding.inventorySha256);assert.equal(report.configurationSha256,a.binding.pins.configuration.sha256);assert.equal(report.catalogSha256,a.binding.pins.catalog.sha256);
assert.equal(report.allArtifactBodiesVerified,true);assert.equal(report.rootGraphAndAliasesAndWorkersIncluded,true);assert.equal(report.retainedHistoricalBridgesIncluded,true);assert.deepEqual(report.failures,[]);assert.equal(report.status,'PASS');assert.equal(report.mode,'full');assert.equal(report.sourcePinsUnchanged,true);assert.deepEqual(report.changedAuthorities,[]);assert.deepEqual(report.comparisonOnlyVersions,[]);assert.equal(report.failedFiles,0);assert.deepEqual(report.skipped,[]);assert.equal(report.uninspectedFiles,0);assert.equal(report.files,2170);assert.equal(report.completedFiles,2170);assert.equal(report.verifiedBytes,656572716);assert.equal(report.expectedBytes,656572716);
const parse=raw=>raw.toString().trim().split('\n').map(JSON.parse);
const rows=parse(await read(path.join(out,'results.jsonl'))),attempts=parse(await read(path.join(out,'attempts.jsonl'))),expected=new Map(a.rows.map(x=>[x.path,x])),grouped=new Map();
assert.equal(rows.length,expected.size);assert.equal(new Set(rows.map(x=>x.path)).size,expected.size);
for(const row of attempts){assert(expected.has(row.path));const e=expected.get(row.path);assert.equal(row.expectedBytes,e.bytes);assert.equal(row.expectedSha256,e.sha256);assert.equal(row.url,new URL(row.path.split('/').map(encodeURIComponent).join('/'),BASE).href);const group=grouped.get(row.path)||[];assert.equal(row.attempt,group.length+1);assert(row.attempt<=3);group.push(row);grouped.set(row.path,group);}
for(const row of rows){const e=expected.get(row.path);assert(e);assert.equal(row.ok,true);assert.equal(row.status,200);assert.equal(row.bytes,e.bytes);assert.equal(row.sha256,e.sha256);assert.equal(row.expectedBytes,e.bytes);assert.equal(row.expectedSha256,e.sha256);assert.equal(row.bytesMatch,true);assert.equal(row.hashMatch,true);assert.equal(row.contentTypeAccepted,true);assert(expectedTypes(row.path).includes((row.contentType||'').split(';')[0].trim().toLowerCase()));assert.equal(row.url,new URL(row.path.split('/').map(encodeURIComponent).join('/'),BASE).href);const group=grouped.get(row.path);assert(group);assert.deepEqual(row,group.at(-1));for(const previous of group.slice(0,-1)){assert.equal(previous.ok,false);assert(isTransient(previous));}assert.equal(row.attempt,group.length);}
assert.equal(grouped.size,expected.size);assert.equal(attempts.length-rows.length,report.retries);
for(const item of files)assert.equal(sha(await fs.readFile(path.join(primary,item.path))),item.sha256,'Input changed during verification.');
await loadAuthority(bindingFile,bindingSha);
const result={format:'revealline-main-public-byte-admission.v1',status:'PASS',verifiedAt:new Date().toISOString(),controllerCommit:a.binding.controllerCommit,controllerTree:a.binding.controllerTree,gameSourceRevision:a.binding.gameSourceRevision,runId:a.binding.runId,deploymentId:a.binding.deploymentId,files:rows.length,bytes:rows.reduce((n,r)=>n+r.bytes,0),retries:report.retries,comparisonOnlyVersions:[],method:'Fresh complete final-deployment HTTP audit',freshWholeInventoryHTTP:true,completeByteAcceptance:true,nativeAcceptance:false,fullyAdmittedSuccessorControllerPending:false,evidence:files,scope:'All final2b public paths, actual MIME and decoded bytes independently reconciled to pinned authority; final51 native/offline acceptance remains separate.'};
await fs.writeFile(path.join(out,'byte-admission.json'),JSON.stringify(result,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:'PASS',files:rows.length,bytes:result.bytes,retries:result.retries,admissionSha256:sha(await fs.readFile(path.join(out,'byte-admission.json')))}));
