export const COPY = {
  en: {
    notebook: 'Flight notebook',
    studio: 'Course Studio',
    authoring: 'Authoring preview · cannot earn',
    offline: 'Prepare offline package',
    removeOffline: 'Remove this offline package',
    offlineReady: 'This exact optional package is ready offline.',
    offlineRemoved: 'This optional package was removed; other installations are unchanged.',
    title: 'FPV · Flight Studio',
    subtitle: 'Civilian practice',
    courses: 'Choose a drill',
    setup: 'Radio & response',
    help: 'Controls',
    close: 'Back to flight',
    arm: 'Arm / resume',
    pause: 'Pause',
    reset: 'Reset',
    fullscreen: 'Full screen',
    source: 'Input',
    keyboard: 'Keyboard',
    touch: 'Touch · Mode 2',
    radio: 'USB radio',
    mode: 'Flight mode',
    'self-level': 'Self-level · manual throttle',
    acro: 'Acro · manual throttle',
    camera: 'Camera',
    fpv: 'First-person',
    chase: 'Chase',
    overview: 'Overview',
    fov: 'Field of view',
    tilt: 'Camera tilt',
    watch: 'Watch example',
    try: 'Try this drill',
    review: 'Review your flight',
    next: 'Next drill',
    replay: 'Replay',
    progress: 'Step',
    altitude: 'Height',
    speed: 'Speed',
    throttle: 'Throttle — lift power',
    contacts: 'Contacts',
    heading: 'Heading',
    pitch: 'Pitch — tilt forward/back',
    roll: 'Roll — tilt left/right',
    yaw: 'Yaw — turn left/right',
    seconds: 'seconds',
    complete: 'Drill complete',
    expired: 'Attempt limit reached. Reset for a new attempt.',
    disarmed: 'Ready on the launch pad. Arm when you are ready.',
    paused: 'Paused. Controls are neutral. Resume explicitly.',
    active: 'Practice in progress',
    demo: 'Verified example · observation only',
    reviewing: 'Your recorded flight · observation only',
    practice: 'Practice',
    endReplay: 'Replay finished. Try starts a new practice attempt.',
    limitation:
      'A fictional civilian training model with simplified dynamics, collision and aircraft response. It does not reproduce a particular aircraft or certify real flight proficiency. No real wiring, radio frequencies or aircraft setup are taught here.',
    keys: 'W / S: pitch forward / back · A / D: roll left / right · Q / E: yaw · ↑ / ↓: adjust manual throttle · Shift: smaller adjustments · P: pause. Release the throttle keys to keep that throttle position. Centre sticks do not stop momentum or hold altitude.',
    touchHelp:
      'Mode 2 illustration: left stick left/right turns (yaw), up/down adjusts lift power (throttle); right stick left/right tilts sideways (roll), up/down tilts forward/back (pitch). Throttle stays at the selected position on release. Losing focus or a pointer pauses and clears controls.',
    modeHelp:
      'Self-level requests a tilt angle and returns toward level with centred pitch/roll. Acro requests an angular rate and retains orientation with centred sticks. Both use manual throttle; neither holds position or altitude.',
    hold: 'Enter the lit volume and settle',
    land: 'Land in the lit pad with low throttle',
    gate: 'Cross the lit gate in the arrow direction',
    steady: 'Consecutive hold',
    velocity: 'Speed limit',
    attitude: 'Tilt limit',
    centre: 'Centre pitch (forward/back tilt), roll (sideways tilt) and yaw (turning)',
    fallback:
      'WebGL is unavailable. The course, controls and learning text remain readable; flying and replay are unavailable in this browser.',
    contextLost:
      'Graphics context lost. The attempt is paused and unchanged. Reload to restore rendering; export your recorded inputs first if needed.',
    focusLost: 'Focus changed. Paused with neutral inputs.',
    selectRadio: 'Choose and calibrate a radio in Radio & response before arming.',
    savedReview:
      'The recorded flight is replay-verified before review. Examples and reviews cannot earn practice completion.',
    export: 'Export recorded inputs',
    imported: 'Replay verified',
    verifying: 'Checking the recorded flight… Closing or changing the drill cancels this check.',
    import: 'Import a recorded flight',
    invalid: 'This recorded flight does not match an available course.',
    inputLabel: 'Live controls · Mode 2 display',
    leftStick: 'Left stick: yaw — left/right · throttle — up/down',
    rightStick: 'Right stick: roll — left/right · pitch — up/down',
    labels: 'Instrument display',
    reduce: 'Reduced motion',
    radioReady: 'Radio verified. Use its arm control or Arm / resume.',
    'select-device': 'Select a radio in setup.',
    'mapping-incomplete': 'Complete radio mapping.',
    'verify-controls': 'Verify the four control directions in setup.',
    'arm-off-first': 'Turn the arm switch off before arming.',
    'pickup-controls': 'Match the paused stick positions shown in setup, then arm.',
    'throttle-high': 'Lower throttle before arming.',
    'centre-controls':
      'Centre pitch (forward/back tilt), roll (sideways tilt) and yaw (turning) before arming.',
    'device-lost': 'Radio lost or replaced. Reconnect and verify before resuming.',
    'invalid-sample': 'Invalid radio input. Recheck the device and calibration.',
    unavailable: 'Gamepad API is unavailable.',
    ready: 'Radio ready to arm.',
  },
  uk: {
    notebook: 'Польотний записник',
    studio: 'Студія вправ',
    authoring: 'Авторський перегляд · без винагород',
    offline: 'Підготувати автономний пакет',
    removeOffline: 'Видалити цей автономний пакет',
    offlineReady: 'Цей точний додатковий пакет готовий автономно.',
    offlineRemoved: 'Цей додатковий пакет видалено; інші встановлення не змінено.',
    title: 'FPV · Студія польоту',
    subtitle: 'Цивільна практика',
    courses: 'Вибрати вправу',
    setup: 'Пульт і реакція',
    help: 'Керування',
    close: 'Назад до польоту',
    arm: 'Увімкнути / продовжити',
    pause: 'Пауза',
    reset: 'Скинути',
    fullscreen: 'На весь екран',
    source: 'Ввід',
    keyboard: 'Клавіатура',
    touch: 'Дотик · Mode 2',
    radio: 'USB-пульт',
    mode: 'Режим польоту',
    'self-level': 'Самовирівнювання · ручний газ',
    acro: 'Acro · ручний газ',
    camera: 'Камера',
    fpv: 'Від першої особи',
    chase: 'Слідом',
    overview: 'Загальний вид',
    fov: 'Поле зору',
    tilt: 'Нахил камери',
    watch: 'Переглянути приклад',
    try: 'Спробувати вправу',
    review: 'Переглянути свій політ',
    next: 'Наступна вправа',
    replay: 'Повтор',
    progress: 'Крок',
    altitude: 'Висота',
    speed: 'Швидкість',
    throttle: 'Газ — сила підйому',
    contacts: 'Контакти',
    heading: 'Курс',
    pitch: 'Тангаж — нахил уперед/назад',
    roll: 'Крен — нахил ліворуч/праворуч',
    yaw: 'Рискання — поворот ліворуч/праворуч',
    seconds: 'секунд',
    complete: 'Вправу завершено',
    expired: 'Досягнуто межу спроби. Скиньте для нової спроби.',
    disarmed: 'Готово на старті. Увімкніть, коли будете готові.',
    paused: 'Пауза. Керування нейтральне. Продовжіть явно.',
    active: 'Триває практика',
    demo: 'Перевірений приклад · лише спостереження',
    reviewing: 'Запис вашого польоту · лише спостереження',
    practice: 'Практика',
    endReplay: 'Перегляд завершено. Спроба починає нову практику.',
    limitation:
      'Вигадана цивільна навчальна модель зі спрощеною динамікою, зіткненнями та реакцією апарата. Вона не відтворює конкретний апарат і не засвідчує вміння реального польоту. Тут немає навчання реальних з’єднань, радіочастот чи налаштування апарата.',
    keys: 'W / S: тангаж уперед / назад · A / D: крен ліворуч / праворуч · Q / E: рискання · ↑ / ↓: змінити ручний газ · Shift: менші корекції · P: пауза. Відпускання клавіш газу зберігає його положення. Центр стіків не зупиняє імпульс і не тримає висоту.',
    touchHelp:
      'Схема Mode 2: лівий стік — рискання / газ, правий — крен / тангаж. Після відпускання газ лишається у вибраному положенні. Втрата фокуса чи вказівника ставить паузу й скидає керування.',
    modeHelp:
      'Самовирівнювання задає кут нахилу й повертає до горизонту з центрованими тангажем і креном. Acro задає кутову швидкість і зберігає орієнтацію з центрованими стіками. Обидва режими мають ручний газ; жоден не тримає положення чи висоту.',
    hold: 'Увійдіть у підсвічений об’єм і стабілізуйте рух',
    land: 'Сядьте на підсвічений майданчик із малим газом',
    gate: 'Пройдіть підсвічені ворота за стрілкою',
    steady: 'Безперервне утримання',
    velocity: 'Межа швидкості',
    attitude: 'Межа нахилу',
    centre: 'Центруйте тангаж, крен і рискання',
    fallback:
      'WebGL недоступний. Вправи, керування та пояснення можна читати; політ і повтор недоступні в цьому браузері.',
    contextLost:
      'Графічний контекст втрачено. Спроба на паузі та збережена в пам’яті. Перезавантажте для відновлення графіки; за потреби спершу експортуйте запис вводу.',
    focusLost: 'Фокус змінився. Пауза з нейтральним вводом.',
    selectRadio: 'Виберіть і відкалібруйте пульт у розділі «Пульт і реакція» перед увімкненням.',
    savedReview:
      'Перед переглядом запис перевіряється повторним відтворенням. Приклади й перегляди не зараховують практику.',
    export: 'Експортувати запис вводу',
    imported: 'Повтор перевірено',
    verifying: 'Перевіряємо запис польоту… Закриття або зміна вправи скасовує перевірку.',
    import: 'Імпортувати запис польоту',
    invalid: 'Запис не відповідає доступній вправі.',
    inputLabel: 'Поточне керування · схема Mode 2',
    leftStick: 'Рискання / газ',
    rightStick: 'Крен / тангаж',
    labels: 'Показники',
    reduce: 'Зменшений рух',
    radioReady: 'Пульт перевірено. Використайте його перемикач або кнопку ввімкнення.',
    'select-device': 'Виберіть пульт у налаштуваннях.',
    'mapping-incomplete': 'Завершіть призначення каналів.',
    'verify-controls': 'Перевірте напрямки чотирьох органів керування.',
    'arm-off-first': 'Вимкніть перемикач перед увімкненням.',
    'pickup-controls':
      'Поверніть стіки до положень паузи, показаних у налаштуваннях, потім увімкніть.',
    'throttle-high': 'Опустіть газ перед увімкненням.',
    'centre-controls': 'Центруйте тангаж, крен і рискання перед увімкненням.',
    'device-lost': 'Пульт втрачено або замінено. Підключіть і перевірте перед продовженням.',
    'invalid-sample': 'Некоректний сигнал пульта. Перевірте пристрій і калібрування.',
    unavailable: 'Gamepad API недоступний.',
    ready: 'Пульт готовий до ввімкнення.',
  },
};
