// Eight independent layouts over the accepted shared r3 Festival scene.
import { xyz } from './art.mjs';

const volume = (type, p, size = [3, 1.8, 3], surface = '$floor') => ({
  type,
  min: xyz(p.map((v, i) => v - size[i] / 2)),
  max: xyz(p.map((v, i) => v + size[i] / 2)),
  ticks: 45,
  maxSpeed: type === 'land' ? 700 : 1000,
  maxTilt: 2500,
  minTilt: 0,
  centred: false,
  heading: null,
  ...(type === 'land' ? { surface } : {}),
});
const hold = (x, y, z) => volume('hold', [x, y, z]);
const home = () => volume('land', [0, 0.6, 25], [4, 1.2, 4]);
const gate = (axis, at, direction, side, height = [2.4, 4.8]) => ({
  type: 'gate',
  axis,
  at: at * 1000,
  direction,
  minSide: side[0] * 1000,
  maxSide: side[1] * 1000,
  minY: height[0] * 1000,
  maxY: height[1] * 1000,
});
const track = (actorId, follow) => ({
  type: 'actor-track-v1',
  actorId,
  minDistance: 4000,
  maxDistance: follow ? 7000 : 8000,
  maxRelativeSpeed: follow ? 1600 : 600,
  maxTilt: follow ? 2500 : 1500,
  ticks: follow ? 300 : 200,
  viewAngle: follow ? 3500 : 2000,
  minTargetTravel: follow ? 4000 : 0,
});

export function festivalCourses(first, revision = 'r4') {
  const row = (
    number,
    activity,
    title,
    ukTitle,
    brief,
    ukBrief,
    lesson,
    ukLesson,
    route,
    actors = [],
  ) => ({
    activity,
    course: {
      ...structuredClone(first),
      id: 'festival-grounds-' + String(number).padStart(2, '0'),
      revision,
      actors,
      locales: {
        en: { title, brief, lesson },
        uk: { title: ukTitle, brief: ukBrief, lesson: ukLesson },
      },
      steps: { 'self-level': structuredClone(route), acro: structuredClone(route) },
    },
  });
  return [
    { activity: 'orientation', course: { ...structuredClone(first), revision } },
    row(
      2,
      'race',
      'Main lawn loop',
      'Коло центральною галявиною',
      'Link the ordered gates around the open central lawn, then return to the entry H. Keep the closed market stalls outside your turns.',
      'Пройдіть упорядковані ворота навколо відкритої галявини й поверніться до літери H біля входу. Залишайте закриті крамнички зовні поворотів.',
      'Look through the next gate before turning. The first loop uses generous lawn space to practise continuous direction changes without cutting through a kiosk.',
      'Дивіться крізь наступні ворота ще до повороту. Широка галявина дає місце для плавної зміни напрямку без зрізання крізь крамничку.',
      [
        gate('z', 18, -1, [-3, 3]),
        gate('x', -10, -1, [8, 14]),
        gate('z', -6, -1, [-13, -7]),
        gate('x', 10, 1, [-6, 0]),
        gate('z', 18, 1, [7, 13]),
        hold(0, 3.8, 22),
        home(),
      ],
    ),
    row(
      3,
      'race',
      'Market slalom',
      'Слалом між крамничками',
      'Enter the west service lane, cross the real gap between the two market rows, and return by the east lane. Painted shutters are closed.',
      'Вийдіть на західну службову смугу, перетніть справжній проміжок між рядами крамничок і поверніться східною смугою. Намальовані віконниці закриті.',
      'Finish the cross-market leg before turning toward the east lane. The picnic table is outside the west path; the narrow table-to-bench gap is not a flight gate.',
      'Завершіть поперечний відрізок ринку перед поворотом на східну смугу. Стіл стоїть поза західною доріжкою; вузький проміжок до лавки не є воротами.',
      [
        hold(-10, 4, 22),
        gate('x', -29, -1, [19, 23]),
        gate('z', 5, -1, [-35, -29]),
        gate('x', -11, 1, [3, 7]),
        gate('x', 11, 1, [3, 7]),
        hold(31.5, 3.6, 5),
        gate('z', 20, 1, [28.5, 34.5]),
        hold(23, 4, 25),
        hold(0, 4, 25),
        home(),
      ],
    ),
    row(
      4,
      'race',
      'Stage-side sprint',
      'Спринт навколо сцени',
      'Sweep behind the stage, come back along its east side and pass through the real open front and side beneath the supported roof.',
      'Облетіть сцену ззаду, поверніться вздовж її східного боку й пройдіть справжні відкриті передню та бічну частини під дахом на опорах.',
      'The rear wall and roof are solid. Brake before the lower under-roof gates and keep clear of the posts and sound desk.',
      'Задня стіна та дах суцільні. Загальмуйте перед нижчими воротами під дахом і тримайтеся осторонь стійок та звукового пульта.',
      [
        hold(-15, 3.6, 12),
        gate('z', -15, -1, [-17, -13]),
        gate('z', -34, -1, [-17, -13]),
        gate('x', 15, 1, [-39, -33], [3, 5]),
        gate('z', -14, 1, [12.5, 17.5], [3, 5]),
        hold(8, 3.6, -11),
        gate('z', -20, -1, [-3, 3], [2.6, 4.2]),
        hold(6, 3.4, -23.5),
        gate('x', 16, 1, [-25.5, -21.5], [2.6, 4.2]),
        hold(15, 5, -8),
        hold(8, 5, 20),
        home(),
      ],
    ),
    row(
      5,
      'precision',
      'Sound-desk landing',
      'Посадка на звуковий пульт',
      'Approach the open stage front and settle on the marked, solid sound-desk top under the roof.',
      'Підійдіть до відкритої передньої частини сцени та сядьте на позначену суцільну стільницю звукового пульта під дахом.',
      'Hold below the front beam, remove horizontal speed and descend onto the real 1.65m support. A landing on the stage floor does not satisfy this objective.',
      'Утримуйтеся нижче передньої балки, приберіть горизонтальну швидкість і опустіться на справжню опору заввишки 1,65м. Посадка на підлогу сцени не зараховується.',
      [
        hold(0, 3.7, -14),
        hold(-2, 3.7, -20),
        volume('land', [-2, 2.25, -22.5], [3, 1.2, 2.4], 'platform-sound-desk'),
      ],
    ),
    row(
      6,
      'follow',
      'Service cart escort',
      'Супровід службового візка',
      'Acquire the civilian cart in the east lane and follow while it actually travels at least four metres. Return to the H after the tracking objective completes.',
      'Знайдіть цивільний службовий візок на східній смузі й супроводжуйте його, доки він справді проїде щонайменше чотири метри. Після завершення стеження поверніться до H.',
      'Keep the subject 4–7m away, inside the nose cone and visible without a wall between you. Match its motion for six continuous seconds; merely waiting nearby does not complete following.',
      'Тримайте об’єкт за 4–7м у напрямку носа й у прямій видимості без стіни між вами. Узгоджуйте рух шість секунд поспіль; простого очікування поруч недостатньо.',
      [
        hold(32, 2.6, 30),
        track('festival-service-cart', true),
        hold(32, 3.5, 26),
        hold(8, 3.5, 24),
        home(),
      ],
      [
        {
          id: 'festival-service-cart',
          type: 'vehicle',
          role: 'civilian',
          position: xyz([32, 0, 6]),
          path: [xyz([32, 0, 6]), xyz([32, 0, 24])],
          speed: 700,
          radius: 800,
          height: 1200,
          fireEveryTicks: 0,
          damage: 0,
        },
      ],
    ),
    row(
      7,
      'observe',
      'Festival guide',
      'Спостереження за гідом',
      'Frame the civilian guide walking slowly beside the stage approach. Keep a steady airborne view, then return to the entry H.',
      'Наведіться на цивільного гіда, який повільно ходить біля підходу до сцени. Утримуйте стабільний вид із повітря, а потім поверніться до H біля входу.',
      'Observe from 4–8m for four continuous seconds with low relative speed and tilt. The real nose-alignment and line-of-sight checks apply in every camera view; no minimum travel is required for observation.',
      'Спостерігайте з 4–8м чотири секунди поспіль із малою відносною швидкістю та нахилом. Перевірки напрямку носа й прямої видимості діють для кожної камери; мінімальний шлях для спостереження не потрібен.',
      [hold(1, 2.2, -4), track('festival-guide', false), hold(0, 3.5, 15), home()],
      [
        {
          id: 'festival-guide',
          type: 'patrol',
          role: 'civilian',
          position: xyz([8, 0, -6]),
          path: [xyz([8, 0, -6]), xyz([8, 0, -2])],
          speed: 300,
          radius: 300,
          height: 1800,
          fireEveryTicks: 0,
          damage: 0,
        },
      ],
    ),
    row(
      8,
      'capstone',
      'Grounds circuit',
      'Коло фестивальним майданчиком',
      'Combine both service lanes, the open space behind the stage and a controlled under-roof visit before the final home landing.',
      'Поєднайте обидві службові смуги, відкритий простір позаду сцени та контрольований проліт під дахом перед завершальною посадкою вдома.',
      'Use the clock, stage and entry arch to orient each leg. Keep the wider perimeter turns distinct from the lower stage passage; every gate must be crossed in order.',
      'Орієнтуйтеся за годинником, сценою й аркою входу. Відділяйте широкі повороти периметром від нижчого проходу сценою; кожні ворота потрібно пройти по порядку.',
      [
        hold(-10, 4, 22),
        gate('x', -31, -1, [19, 25]),
        gate('z', -34, -1, [-35, -29]),
        gate('x', 30, 1, [-40, -34]),
        gate('z', 20, 1, [29, 35]),
        hold(8, 5, 18),
        gate('z', -12, -1, [-3, 3], [3, 5]),
        hold(0, 3.5, -20),
        hold(7, 3.5, -22),
        hold(15, 4, -10),
        hold(6, 4, 20),
        home(),
      ],
    ),
  ];
}
