// Supplementary prompts use the source-linked discoveries already authored for
// each mission. They add no claims about real participants or internal practice.
const rows = {
  'social-drone-people-workshop': [
    [
      'Together, point to one welcoming detail in the fictional room. Which words describe the artwork, and which words describe the community’s stated purpose?',
      'Разом знайдіть одну привітну деталь у вигаданій кімнаті. Які слова описують ілюстрацію, а які — заявлену мету спільноти?',
      'Make two headings: “Public purpose” and “Imagined room.” Place one sentence under each. An attractive room does not prove a real event occurred.',
      'Створіть два заголовки: «Публічна мета» й «Уявна кімната». Додайте по реченню. Приваблива кімната не доводить, що відбулася реальна подія.',
      'Compare the public description with the gallery caption. Identify the origin of each claim and rewrite any sentence that accidentally implies endorsement.',
      'Порівняйте публічний опис із підписом галереї. Визначте походження кожного твердження й перепишіть речення, яке ненавмисно натякає на схвалення.',
    ],
    [
      'Imagine preparing a small book display together. One person writes labels and another welcomes visitors. Explain how each helps the other.',
      'Уявіть, що разом готуєте невелику книжкову виставку. Одна людина пише підписи, інша зустрічає гостей. Поясніть, як вони допомагають одна одній.',
      'Choose two different contributions. Describe what each needs from the other without ranking the people or assuming equal time and resources.',
      'Оберіть два різні внески. Опишіть, що кожен потребує від іншого, не оцінюючи людей і не припускаючи однакового часу й ресурсів.',
      'Sketch a dependency between two fictional roles. Add an alternative if one person cannot participate; keep the purpose while changing the arrangement.',
      'Накресліть залежність між двома вигаданими ролями. Додайте альтернативу, якщо хтось не може долучитися: збережіть мету, змінивши організацію.',
    ],
    [
      'Read “A community learning room” and “A real workshop last Tuesday.” Which caption can our invented picture support? Explain your choice together.',
      'Прочитайте «Кімната спільного навчання» та «Реальна майстерня минулого вівторка». Який підпис підтримує вигаданий малюнок? Разом поясніть вибір.',
      'Pair each claim with its evidence: the official page for stated purpose, the artwork for its visible fictional details. Leave unsupported claims unconfirmed.',
      'Поєднайте твердження з доказом: офіційна сторінка — для заявленої мети, ілюстрація — для видимих вигаданих деталей. Непідтверджене залиште невизначеним.',
      'Write a source note that separates creator, publication date and what the source actually establishes. State one question it cannot answer.',
      'Складіть примітку, що розрізняє автора, дату публікації та те, що джерело справді підтверджує. Назвіть запитання, на яке воно не відповідає.',
    ],
    [
      'Choose one unfamiliar word on a fictional display label. Ask someone “What is its job?” and listen for an explanation you can repeat.',
      'Оберіть незнайоме слово на вигаданому підписі. Запитайте «Яка його роль?» і вислухайте пояснення, яке зможете переказати.',
      'Before choosing a course, separate the question you want answered from the scope the provider states. Assembly and flight training are different scopes.',
      'Перш ніж обрати курс, відокремте власне запитання від заявленої програми. Навчання складання й навчання польотів мають різний зміст.',
      'Turn a broad request into one bounded question with context and uncertainty. Identify which source could answer it and what still needs an instructor.',
      'Перетворіть широкий запит на одне конкретне запитання з контекстом і невизначеністю. Вкажіть доречне джерело й те, що ще потребує наставника.',
    ],
    [
      'Compare “checked” with the longer fictional note. Find who checked the label and what remains unknown. Why would the next person prefer that detail?',
      'Порівняйте «перевірено» з довшою вигаданою нотаткою. Знайдіть, хто перевірив підпис і що лишилося невідомим. Чому це допоможе наступній людині?',
      'Rewrite “all done” as three short parts: what was checked, the evidence, and what remains open. Use only the facts in the fictional card.',
      'Перепишіть «усе готово» трьома короткими частинами: що перевірили, які докази маємо та що лишилося відкритим. Використовуйте лише факти вигаданої картки.',
      'Design a review note for a different civilian display task. Distinguish an observation, the reviewer’s judgement and an unresolved question.',
      'Складіть нотатку перевірки для іншого цивільного виставкового завдання. Розрізніть спостереження, висновок перевіряльника й нерозв’язане запитання.',
    ],
    [
      'Choose two collected cards and explain their connection to a partner. Swap roles: can your partner describe the same connection differently?',
      'Оберіть дві зібрані картки й поясніть їхній зв’язок партнерові. Поміняйтеся ролями: чи можна пояснити його інакше?',
      'Plan the next step for the fictional library display. Include its purpose, one source and the information the next helper needs.',
      'Сплануйте наступний крок для вигаданої бібліотечної виставки. Вкажіть мету, одне джерело та відомості, потрібні наступному помічникові.',
      'Transfer the six-card routine to a new community learning fixture. Explain which principles transfer and which organisational details you cannot assume.',
      'Перенесіть підхід шести карток до нового завдання спільного навчання. Поясніть, які принципи переносяться, а які організаційні деталі не можна припускати.',
    ],
  ],
  'social-drone-community-connections': [
    [
      'Describe the library event to someone who has not seen the room. Can they name its audience and purpose?',
      'Опишіть бібліотечну подію людині, яка не бачила кімнати. Чи може вона назвати аудиторію й мету?',
      'Underline the audience, purpose and result in the useful brief. Add a question where a necessary detail is missing.',
      'Підкресліть аудиторію, мету й результат у корисному описі. Додайте запитання там, де бракує потрібної деталі.',
      'Rewrite the same brief for a different fictional audience. Preserve its purpose and distinguish an agreed responsibility from an assumption.',
      'Перепишіть опис для іншої вигаданої аудиторії. Збережіть мету й розрізніть узгоджену відповідальність та припущення.',
    ],
    [
      'Use twelve paper marks for expected booklets. Circle eight received, then two more. How many are still missing?',
      'Позначте на папері дванадцять очікуваних буклетів. Обведіть вісім отриманих, потім ще два. Скількох бракує?',
      'Keep expected and received counts separate. Explain why receiving two more changes both the received and missing counts.',
      'Ведіть очікувану й отриману кількість окремо. Поясніть, чому ще два буклети змінюють і отриману кількість, і нестачу.',
      'Propose a small record that another volunteer can reconcile after a later delivery. Retain the observation behind each update.',
      'Запропонуйте короткий запис, який інший волонтер зможе звірити після наступної доставки. Збережіть спостереження, що обґрунтовує кожне оновлення.',
    ],
    [
      'Read the unfinished-label note aloud. What does the next helper need to know before starting?',
      'Прочитайте вголос нотатку про незавершений підпис. Що має знати наступний помічник?',
      'Separate “someone is proposed” from “someone agreed.” Add the remaining item and next action to the handoff.',
      'Розрізніть «когось запропоновано» та «людина погодилася». Додайте до передачі незавершений пункт і наступну дію.',
      'Inspect the handoff for hidden assumptions about ownership and evidence. Rewrite it so a new reader can continue without guessing.',
      'Перевірте передачу справ на приховані припущення про відповідальність і докази. Перепишіть її так, щоб новий читач продовжив без здогадок.',
    ],
    [
      'Give directions without naming a colour. Could a partner find the fictional reading room from your words?',
      'Поясніть шлях без назви кольору. Чи знайде партнер вигадану читальню за вашими словами?',
      'Arrange the invitation under Where, When and What to expect. Keep colour as extra information, not the only direction.',
      'Розподіліть запрошення за рубриками «Де», «Коли», «Чого очікувати». Залиште колір додатковою, а не єдиною підказкою.',
      'Review a fictional invitation for dependence on sight, assumed local knowledge and ambiguous instructions. Propose one concrete improvement for each.',
      'Перевірте вигадане запрошення на залежність від зору, знання місцевості та нечітких вказівок. Запропонуйте конкретне поліпшення для кожного випадку.',
    ],
    [
      'Ask a partner what they need from the room map. Describe the feature that answers that question before decorative details.',
      'Запитайте партнера, що йому потрібно дізнатися з плану кімнати. Спершу опишіть доречну ознаку, а вже потім прикраси.',
      'Compare “nice picture” with a description that locates the reading room. Explain what useful information the second gives.',
      'Порівняйте «гарний малюнок» з описом розташування читальні. Поясніть, яку корисну інформацію дає другий варіант.',
      'Write two text alternatives for the same fictional image in two different contexts. Explain why the essential information changes.',
      'Напишіть два текстові описи одного вигаданого зображення для різних контекстів. Поясніть, чому змінюється суттєва інформація.',
    ],
    [
      'The notice promised twelve, but ten booklets are ready. Together, write a correction that a newcomer can understand.',
      'Оголошення обіцяло дванадцять буклетів, але готові десять. Разом напишіть зрозуміле новачкові виправлення.',
      'Keep “available now” separate from “expected later.” Identify where the old notice must be replaced so the correction is useful.',
      'Розділіть «доступно зараз» і «очікується пізніше». Визначте, де слід замінити старе оголошення, щоб виправлення допомогло.',
      'Audit the six-card communication chain from a newcomer’s perspective. Locate one unsupported promise and trace the correction to its evidence.',
      'Перевірте послідовність шести карток очима новачка. Знайдіть необґрунтовану обіцянку й пов’яжіть виправлення з доказом.',
    ],
  ],
  'victory-drones-knowledge-connects': [
    [
      'Choose one part in the imagined science room and ask what job it does. Keep the question small enough to explain together.',
      'Оберіть деталь в уявній науковій кімнаті й запитайте про її роль. Нехай запитання буде достатньо конкретним для спільного пояснення.',
      'Turn “learn everything” into a question about one role or relationship. Name the kind of source that could answer it.',
      'Перетворіть «дізнатися все» на запитання про одну роль або зв’язок. Назвіть тип джерела, яке допоможе.',
      'Define a learning question, an appropriate source and a stopping point. Explain what evidence would count as an answer.',
      'Визначте навчальне запитання, доречне джерело й межу дослідження. Поясніть, які докази дадуть відповідь.',
    ],
    [
      'Explain a bookshelf with words, then a simple sketch. Ask a partner what became clearer in each version.',
      'Поясніть книжкову полицю словами, потім простим малюнком. Запитайте партнера, що стало зрозумілішим у кожному варіанті.',
      'Choose one relationship and show it two ways. Identify what the diagram highlights and what the everyday example adds.',
      'Оберіть зв’язок і покажіть його двома способами. Визначте, що підкреслює схема й що додає побутовий приклад.',
      'Compare the explanatory value and evidential limits of a diagram and an example. Add a source rather than treating either format as proof.',
      'Порівняйте пояснювальну цінність і доказові межі схеми та прикладу. Додайте джерело замість сприйняття форми як доказу.',
    ],
    [
      'A card says “it worked.” Ask together: what worked, and how do we know?',
      'Картка каже «це спрацювало». Разом запитайте: що саме й звідки ми знаємо?',
      'Separate a reported result from the evidence supporting it. List one missing detail before repeating the claim.',
      'Відокремте повідомлений результат від його доказів. Назвіть одну відсутню деталь, перш ніж повторити твердження.',
      'Trace a claim to its source and identify the gap between a project’s stated mission and a particular outcome. Keep that gap explicit.',
      'Простежте твердження до джерела й визначте різницю між заявленою місією проєкту та конкретним результатом. Явно збережіть цю відмінність.',
    ],
    [
      'Take turns finishing “I understand this part, but wonder about…” There is no reading race.',
      'По черзі завершіть фразу «Цю частину я розумію, але хочу з’ясувати…». Це не змагання зі швидкості читання.',
      'Name a part you recognize and a relationship you cannot yet explain. That distinction gives your next question a useful focus.',
      'Назвіть деталь, яку впізнаєте, і зв’язок, який ще не можете пояснити. Це допоможе сформулювати наступне запитання.',
      'Design a feedback question that reveals uncertainty without grading a person’s confidence. Explain how the answer would change the next explanation.',
      'Складіть запитання для зворотного зв’язку, що виявляє невизначеність без оцінювання впевненості людини. Поясніть, як відповідь змінить наступне пояснення.',
    ],
    [
      'Look at a diagram and a photograph. Ask the same question about both and compare what each lets you answer.',
      'Розгляньте схему та фотографію. Поставте до них однакове запитання й порівняйте можливі відповіді.',
      'Choose whether you need appearance or a relationship. Match the source to that question and state what stays unknown.',
      'Визначте, що вам потрібно: зовнішній вигляд чи зв’язок. Доберіть джерело до запитання й назвіть невідоме.',
      'Evaluate two representations against the same question, scale and assumptions. Separate visual realism from the reliability of the claim.',
      'Оцініть два зображення за однаковим запитанням, масштабом і припущеннями. Відокремте візуальну реалістичність від надійності твердження.',
    ],
    [
      'Explain one bicycle part to an imaginary newcomer. Invite them to ask one question back.',
      'Поясніть роль однієї деталі велосипеда уявному новачкові. Запропонуйте поставити запитання у відповідь.',
      'Use four steps: question, relationship, source, limit. Try them on an everyday system different from the gallery example.',
      'Скористайтеся чотирма кроками: запитання, зв’язок, джерело, межа. Застосуйте їх до іншої побутової системи.',
      'Build a short explanation, then test it with a counterexample or changed assumption. Revise the explanation without overstating what it establishes.',
      'Складіть коротке пояснення й перевірте його контрприкладом або зміненим припущенням. Уточніть його, не перебільшуючи висновків.',
    ],
  ],
  'victory-drones-ideas-understanding': [
    [
      'Point to the sentence that reports what the cart did. Which other sentence tries to explain why?',
      'Знайдіть речення, що описує рух візка. Яке інше речення намагається пояснити причину?',
      'Write the observation and possible explanation on separate cards. Name another difference that could affect the result.',
      'Запишіть спостереження й можливе пояснення на окремих картках. Назвіть іншу відмінність, що могла вплинути на результат.',
      'Identify competing explanations for the same fictional observation. State what further comparison could distinguish them.',
      'Визначте різні пояснення одного вигаданого спостереження. Опишіть додаткове порівняння, що допоможе їх розрізнити.',
    ],
    [
      'Draw one arrow on the hand and another on the wall. Say which object each arrow belongs to.',
      'Намалюйте одну стрілку на руці, іншу — на стіні. Назвіть об’єкт, якому належить кожна.',
      'Separate the two interacting objects before drawing their force pair. Explain why arrows on different objects are not summed as forces on one object.',
      'Спершу розділіть два об’єкти взаємодії, потім намалюйте пару сил. Поясніть, чому сили на різних тілах не додають як сили на одному.',
      'Contrast an interaction pair with two balancing forces on one object. Use labels that make the object of each force explicit.',
      'Порівняйте пару сил взаємодії з двома врівноваженими силами на одному тілі. Підпишіть, на яке тіло діє кожна сила.',
    ],
    [
      'Imagine a cart already moving straight. In the idealized equal-force picture, does zero change in motion mean it must stop?',
      'Уявіть візок, що вже рухається прямо. Чи означає нульова зміна руху в ідеалізованій схемі рівних сил, що він мусить зупинитися?',
      'List forces acting on one cart, including directions. Distinguish zero net force from zero velocity.',
      'Перелічіть сили, що діють на один візок, разом із напрямками. Розрізніть нульову рівнодійну та нульову швидкість.',
      'State the initial velocity and included external forces before predicting a change. Identify how omitted resistance would change the model’s adequacy.',
      'Зазначте початкову швидкість і враховані зовнішні сили, перш ніж передбачати зміну. Поясніть, як пропущений опір вплине на придатність моделі.',
    ],
    [
      'Make two equal-length paper arrows pointing different ways. What is the same and what differs?',
      'Зробіть дві паперові стрілки однакової довжини з різними напрямками. Що збігається, а що відрізняється?',
      'Describe each arrow with both magnitude and direction. Explain why the number alone leaves the description incomplete.',
      'Опишіть кожну стрілку величиною та напрямком. Поясніть, чому самого числа недостатньо.',
      'Check a diagram’s scale before comparing arrow lengths. Propose a caption that distinguishes equal magnitude from equal vectors.',
      'Перевірте масштаб схеми перед порівнянням довжин стрілок. Запропонуйте підпис, що розрізняє рівні величини й рівні вектори.',
    ],
    [
      'Two things changed in the cart story. Circle both. Can the result tell us which change mattered?',
      'В історії візка змінилися дві речі. Обведіть обидві. Чи показує результат, яка зміна мала значення?',
      'On paper, name what changes, what stays alike and what is observed. Add one possible source of measurement uncertainty.',
      'На папері назвіть, що змінюється, що лишається однаковим і що спостерігають. Додайте можливе джерело похибки вимірювання.',
      'Review the proposed comparison for confounded changes and inconsistent measurement. Describe what evidence would support a narrower conclusion.',
      'Перевірте порівняння на змішані зміни й непослідовне вимірювання. Опишіть докази для обережнішого висновку.',
    ],
    [
      'Explain the book-on-table picture to a partner. Name what the simple picture leaves out.',
      'Поясніть партнерові малюнок книжки на столі. Назвіть те, чого проста схема не показує.',
      'Give your model an intended use, an assumption and a limit. A useful model does not need to reproduce everything.',
      'Визначте призначення моделі, припущення та межу. Корисна модель не мусить відтворювати все.',
      'Transfer the reasoning to a different everyday system. State when your simplified model is useful and what observation would make you revise it.',
      'Перенесіть міркування на іншу побутову систему. Вкажіть, коли спрощена модель корисна й яке спостереження змусить її переглянути.',
    ],
  ],
};
const titles = {
  families: ['Try it together', 'Спробуйте разом'],
  beginners: ['Build the connection', 'Зрозумійте зв’язок'],
  hobbyists: ['Question the evidence', 'Дослідіть докази'],
};
export const COMMUNITY_LEARNING_PROFILES = Object.fromEntries(
  Object.entries(rows).flatMap(([campaign, missions]) =>
    missions.map((row, index) => [
      `${campaign}-${String(index + 1).padStart(2, '0')}`,
      Object.fromEntries(
        Object.entries(titles).map(([id, title], profileIndex) => [
          id,
          Object.fromEntries(
            ['en', 'uk'].map((locale, localeIndex) => [
              locale,
              { title: title[localeIndex], paragraphs: [row[profileIndex * 2 + localeIndex]] },
            ]),
          ),
        ]),
      ),
    ]),
  ),
);
