// Eight independent layouts over the accepted r2 quay. Coordinates are metres.
import { xyz } from './art.mjs';
const volume = (type, p, size = [3, 1.8, 3], surface = 'platform-quay') => ({
  type,
  min: xyz(p.map((v, i) => v - size[i] / 2)),
  max: xyz(p.map((v, i) => v + size[i] / 2)),
  ticks: 45,
  maxSpeed: type === 'land' ? 700 : 1000,
  maxTilt: 2500,
  minTilt: 0,
  centred: false,
  heading: null,
  ...(type === 'land' ? { surface } : {}),
});
const hold = (x, y, z) => volume('hold', [x, y, z]);
const home = () => volume('land', [-2, 2.6, 34], [4, 1.2, 4]);
const gate = (axis, at, direction, side, height = [4, 6]) => ({
  type: 'gate',
  axis,
  at: at * 1000,
  direction,
  minSide: side[0] * 1000,
  maxSide: side[1] * 1000,
  minY: height[0] * 1000,
  maxY: height[1] * 1000,
});
const track = (actorId, follow) => ({
  type: 'actor-track-v1',
  actorId,
  minDistance: 4000,
  maxDistance: follow ? 7000 : 8000,
  maxRelativeSpeed: follow ? 1600 : 600,
  maxTilt: follow ? 2500 : 1500,
  ticks: follow ? 300 : 200,
  viewAngle: follow ? 3500 : 2000,
  minTargetTravel: follow ? 4000 : 0,
});
export function harborCourses(first, revision = 'r3') {
  const row = (
    number,
    activity,
    title,
    ukTitle,
    brief,
    ukBrief,
    lesson,
    ukLesson,
    route,
    actors = [],
  ) => ({
    activity,
    course: {
      ...structuredClone(first),
      id: 'harbor-docks-' + String(number).padStart(2, '0'),
      revision,
      actors,
      locales: {
        en: { title, brief, lesson },
        uk: { title: ukTitle, brief: ukBrief, lesson: ukLesson },
      },
      steps: { 'self-level': structuredClone(route), acro: structuredClone(route) },
    },
  });
  return [
    { activity: 'orientation', course: { ...structuredClone(first), revision } },
    row(
      2,
      'race',
      'Container perimeter',
      'Периметр контейнерів',
      'Cross the open apron south of the containers, follow their west edge, then return through the broad east corridor.',
      'Перетніть відкритий майданчик на південь від контейнерів, пройдіть уздовж західного краю та поверніться широким східним коридором.',
      'The doors and all container stacks are solid. Follow the ordered perimeter gates; do not cut through the narrow gaps between adjacent boxes.',
      'Двері та всі штабелі контейнерів суцільні. Пройдіть ворота периметра по порядку; не зрізайте крізь вузькі щілини між сусідніми контейнерами.',
      [
        hold(-8, 5, 18),
        gate('x', -25, -1, [13, 17]),
        hold(-39, 5, 15),
        gate('z', -10, -1, [-41, -37]),
        gate('z', -32, -1, [-41, -37]),
        hold(-39, 5, -38),
        gate('x', -7, 1, [-41, -35]),
        gate('z', 10, 1, [-10, -4]),
        hold(-6, 5, 24),
        home(),
      ],
    ),
    row(
      3,
      'race',
      'Gantry height line',
      'Висотна траєкторія порталу',
      'Climb through the real gantry opening, turn beyond its north beam and return down the clear waterside corridor.',
      'Підніміться крізь справжній отвір порталу, поверніть за північною балкою та спустіться вільним коридором уздовж причалу.',
      'The blue beams and operator cabin are closed solids. Stay below the quayside boom and inside the visible concrete boundary; the barge is scenery outside this area.',
      'Сині балки й кабіна оператора суцільні. Тримайтеся нижче стріли та всередині видимої бетонної межі; баржа є декорацією поза цією зоною.',
      [
        hold(23, 6, 22),
        gate('z', 1, -1, [20, 26], [5, 8]),
        gate('z', -14, -1, [20, 26], [12, 15]),
        hold(23, 16, -32),
        gate('x', 34, 1, [-37, -31], [17, 20]),
        hold(36, 18, -30),
        gate('z', 7, 1, [35, 37.5], [11, 14]),
        hold(24, 9, 23),
        home(),
      ],
    ),
    row(
      4,
      'precision',
      'Service-deck landing',
      'Посадка на службовий майданчик',
      'Approach from the open east side and settle on the bordered H of the supported service deck.',
      'Підійдіть із відкритого східного боку й сядьте на обведену літеру H службового майданчика на опорах.',
      'Remove horizontal speed above the real 5.5m deck before descending. The adjacent office roof is higher; landing on the quay or office does not satisfy this target.',
      'Приберіть горизонтальну швидкість над справжнім майданчиком заввишки 5,5м перед зниженням. Дах офісу поряд вищий; посадка на причал чи офіс не зараховується.',
      [
        hold(-4, 9, 32),
        hold(-15.5, 9, 31.5),
        volume('land', [-15.5, 6.1, 31.5], [4, 1.2, 4], 'platform-service-deck'),
      ],
    ),
    row(
      5,
      'follow',
      'Terminal cart escort',
      'Супровід портового візка',
      'Acquire the civilian service cart on the central land-side lane and follow its actual travel before returning to the quay H.',
      'Знайдіть цивільний службовий візок на центральній смузі суходолу й супроводжуйте його справжній рух перед поверненням до H на причалі.',
      'Keep 4–7m range, match speed and hold the subject in the nose view for six continuous seconds while it travels at least four metres. No weapons are used in this layout.',
      'Тримайте відстань 4–7м, узгодьте швидкість і утримуйте об’єкт у напрямку носа шість секунд поспіль, доки він проїде щонайменше чотири метри. У цьому маршруті немає застосування зброї.',
      [hold(4, 4.5, 29), track('harbor-service-cart', true), hold(4, 5, 25), home()],
      [
        {
          id: 'harbor-service-cart',
          type: 'vehicle',
          role: 'civilian',
          position: xyz([4, 2, 0]),
          path: [xyz([4, 2, 0]), xyz([4, 2, 18])],
          speed: 700,
          radius: 800,
          height: 1200,
          fireEveryTicks: 0,
          damage: 0,
        },
      ],
    ),
    row(
      6,
      'observe',
      'Deck inspection',
      'Огляд службового майданчика',
      'Observe the civilian inspector walking on the raised service deck from the open east side, then return to the quay.',
      'Спостерігайте за цивільним інспектором на піднятому службовому майданчику з відкритого східного боку, потім поверніться на причал.',
      'Hold a steady 4–8m view for four continuous seconds with low relative speed and tilt. The walker has real support at 5.5m; no minimum travel is required for this observation.',
      'Утримуйте стабільний вид із відстані 4–8м чотири секунди поспіль із малою відносною швидкістю та нахилом. Під пішоходом є справжня опора на висоті 5,5м; мінімальний шлях для спостереження не потрібен.',
      [hold(-5, 7.2, 31), track('harbor-deck-inspector', false), hold(-4, 8, 33), home()],
      [
        {
          id: 'harbor-deck-inspector',
          type: 'patrol',
          role: 'civilian',
          position: xyz([-15.5, 5.5, 30]),
          path: [xyz([-15.5, 5.5, 30]), xyz([-15.5, 5.5, 33.5])],
          speed: 300,
          radius: 300,
          height: 1800,
          fireEveryTicks: 0,
          damage: 0,
        },
      ],
    ),
    row(
      7,
      'combat',
      'Training-drone bay',
      'Майданчик навчального дрона',
      'Visit the clear north gantry bay and disable one fictional stationary training drone with the simulator pulse control, then return to the H.',
      'Вийдіть на вільний північний майданчик порталу й вимкніть один вигаданий нерухомий навчальний дрон імпульсом симулятора, потім поверніться до H.',
      'This isolated layout contains no civilian subjects and the target does not fire. Keep the nose aligned and use the existing fire action from a safe standoff; ordinary simulated projectiles and target health determine completion.',
      'Цей окремий маршрут не містить цивільних об’єктів, а мішень не стріляє. Спрямуйте ніс і використайте наявну дію пострілу з безпечної відстані; завершення визначають звичайні модельовані снаряди та здоров’я мішені.',
      [
        hold(23, 8, 22),
        hold(23, 10, -24),
        { type: 'eliminate', targets: ['harbor-training-drone'] },
        hold(23, 10, -20),
        hold(23, 8, 22),
        home(),
      ],
      [
        {
          id: 'harbor-training-drone',
          type: 'drone',
          role: 'hostile',
          position: xyz([23, 10, -38]),
          path: [],
          speed: 0,
          radius: 500,
          height: 1000,
          health: 50,
          fireEveryTicks: 0,
          damage: 0,
          range: 12500,
        },
      ],
    ),
    row(
      8,
      'capstone',
      'Harbor circuit',
      'Коло портом',
      'Combine the north container edge, gantry height change and open south apron, ending with a controlled landing on the service deck.',
      'Поєднайте північний край контейнерів, зміну висоти біля порталу та відкритий південний майданчик, завершивши точною посадкою на службову платформу.',
      'Use the numbered gantry and painted deck to orient the ordered line. The cross-terminal leg goes north of every container; finish above the deck rather than descending through its support structure.',
      'Орієнтуйтеся за номером порталу та розміткою платформи. Поперечний відрізок проходить північніше всіх контейнерів; завершуйте над платформою, не знижуючись крізь її опори.',
      [
        hold(-7, 6, 16),
        gate('z', -35, -1, [-10, -4], [5, 7]),
        hold(-7, 7, -40),
        gate('x', 23, 1, [-43, -37], [8, 11]),
        hold(23, 12, -32),
        gate('z', 2, 1, [20, 26], [12, 15]),
        hold(23, 9, 22),
        hold(-4, 9, 24),
        hold(-15.5, 9, 31.5),
        volume('land', [-15.5, 6.1, 31.5], [4, 1.2, 4], 'platform-service-deck'),
      ],
    ),
  ];
}
