import test from 'node:test';
import assert from 'node:assert/strict';
import { createDefaultThemeBundle, ASSET_SLOTS } from '../presentation/catalog.mjs';
import { validateThemeBundle } from '../presentation/model.mjs';
import { adoptStudioBundle } from '../presentation/studio-session.mjs';
import {
  OVERFLIGHT_FIELD_KIT_IDS,
  overflightFieldKitArt,
} from '../presentation/overflight-field-kit-art.mjs';
import { overflightEffectPose } from '../presentation/overflight-motion.mjs';
import { produceOverflightAssets } from '../../scripts/produce-overflight-assets.mjs';

test('new reusable source sprites keep exact optional Asset Studio contracts and generated bytes', async () => {
  for (const id of OVERFLIGHT_FIELD_KIT_IDS) {
    const slot = ASSET_SLOTS.find((row) => row.id === id);
    assert.equal(slot.required, false);
    assert.deepEqual(slot.dimensions, { width: 16, height: 16 });
    assert.ok(slot.recipes.includes('pickup.icon.v1'));
    assert.ok(slot.screens.includes('studio'));
    assert.ok(overflightFieldKitArt(id).rgba.some((byte) => byte));
  }
  assert.equal((await produceOverflightAssets({ check: true })).assets, 13);
});
test('older Studio workspaces admit only exact registered new slots without rewriting history', () => {
  const incoming = createDefaultThemeBundle();
  const old = structuredClone(incoming);
  const newSlots = new Set(OVERFLIGHT_FIELD_KIT_IDS);
  old.slots = old.slots.filter((row) => !newSlots.has(row.id));
  old.assets = old.assets.filter((row) => !newSlots.has(row.slot));
  for (const theme of old.themes) for (const id of newSlots) delete theme.bindings[id];
  for (const collection of old.collections)
    for (const id of newSlots) delete collection.bindings[id];
  validateThemeBundle(old);
  const before = structuredClone(old);
  const adopted = adoptStudioBundle(old, incoming);
  assert.deepEqual(old, before);
  for (const id of newSlots)
    assert.deepEqual(
      adopted.slots.find((row) => row.id === id),
      incoming.slots.find((row) => row.id === id),
    );
  const altered = structuredClone(incoming);
  altered.slots.find((row) => row.id === OVERFLIGHT_FIELD_KIT_IDS[0]).dimensions.width = 32;
  assert.throws(() => adoptStudioBundle(old, altered));
});
test('reduced effects preserve full hostile warning visibility while simplifying cosmetics', () => {
  for (const kind of ['warning', 'arrival', 'hostile-impact']) {
    assert.deepEqual(
      overflightEffectPose({ kind, age: 0.2, life: 1, reducedEffects: true }),
      overflightEffectPose({ kind, age: 0.2, life: 1, reducedEffects: false }),
    );
  }
  assert.ok(
    overflightEffectPose({ kind: 'pulse', age: 0.2, life: 1, reducedEffects: true }).alpha <
      overflightEffectPose({ kind: 'pulse', age: 0.2, life: 1, reducedEffects: false }).alpha,
  );
});
