export const OVERFLIGHT_COPY = Object.freeze({
  en: {
    yourAirframe: 'Flight deck',
    character: 'Choose your drone',
    characterLocked:
      'Airframe locked for this sortie. Choose another drone before starting a new sortie.',
    characterHint:
      'Your look, your flight. All airframes share the same handling and upgrades for now.',
    battlefieldEffects: 'Battlefield effects',
    keepRemains: 'Keep enemy remains on the battlefield',
    remainsHint:
      'Shared with the main game. The oldest traces are recycled to keep the battlefield responsive.',
    retrySaving: 'Retry saving',
    sortie: 'Sortie',
    spareAirframes: 'Spare airframes',
    airframeActive: 'Active airframe',
    levelReached: 'Level reached',
    upgradeInstalled: 'Upgrade installed',
    evolutionInstalled: 'Evolution unlocked',
    debrief: 'Flight report',
    victoryKicker: 'Field cleared',
    lossKicker: 'Signal lost',
    victoryMessage: 'Final target down. This battlefield tells your story.',
    lossMessage: 'Every pass made a difference. Take what you learned into the next sortie.',
    upgradesEarned: 'Upgrades earned',
    eliteCleared: 'Elite defeated',
    finalCleared: 'Final tank defeated',
    evolvedBuild: 'Weapon evolved',
    intactSortie: 'No airframes lost',
    boostsUsed: 'Boosts used',
    flightLevel: 'Flight level',
    title: 'Overflight',
    preparing: 'Preparing Overflight…',
    briefing:
      'Fly through the gaps. Your payload fires automatically as you fly. Collect salvage, build your equipment and defeat the final tank.',
    field: 'Encounters',
    installed: 'Installed encounters',
    exportEncounter: 'Export',
    removeEncounter: 'Remove',
    removeLocalEncounter: 'Remove local copy',
    localEncounterRemoved: 'Local copy removed. The Community edition is still installed.',
    communityEncounterOwner: 'Managed in Community',
    communityEncounterRecovery:
      'Keep an exact recovery package and manage this edition in Community.',
    encounterRemoved: 'Removed from the installed list. The current sortie is unchanged.',
    noInstalled: 'Install an Overflight package in Studio to play it here.',
    libraryFailed: 'Installed encounters could not be loaded.',
    startHint:
      'WASD / arrows · Space boost · Escape pause. Controller uses your shared saved mapping; without one, left stick / RT / Menu. Radios need a saved shared setup.',
    help: 'Skim the crowd edge so your payload lands among the pursuers. Salvage remains on the ground. Each level pauses the sortie for one of three upgrades. Enemy warnings lock before the attack; move out of their path. Defeat the final tank to complete the sortie.',
    settings: 'Sortie settings',
    language: 'Language',
    airframes: 'Airframes',
    oneAirframe: 'One airframe',
    threeAirframes: 'Three airframes · build retained',
    slowResume: 'Brief slow motion after an upgrade',
    nextSortie: 'Sortie options apply on the next Start or Retry.',
    textFace: 'Text face',
    themeText: 'Theme font',
    plainText: 'Plain',
    textSize: 'Text size',
    standard: 'Standard',
    large: 'Large',
    reduced: 'Reduced effects',
    volume: 'Master volume',
    muted: 'Mute',
    hull: 'Hull',
    boost: 'Boost',
    level: 'Level',
    kills: 'Cleared',
    upgrades: 'Choose an upgrade',
    upgradeHint: 'Combat is paused. Compare the patterns, then choose your next upgrade.',
    combatModule: 'Combat',
    supportModule: 'Support',
    oneTimeUpgrade: 'One-time boost',
    pulseCharge: 'Pulse flight charge',
    flyToCharge: 'Fly to charge a stronger pulse',
    current: 'Now',
    next: 'Next',
    evolution: 'Evolution',
    reroll: 'Reroll',
    rerolls: 'rerolls left',
    emptySlot: 'Empty slot',
    ready: 'Ready',
    won: 'Sortie complete',
    lost: 'Sortie ended',
    elapsed: 'Time',
    salvage: 'Salvage',
    build: 'Your build',
    resultHint: 'Try another combination on the same battlefield.',
    workshop: 'Overflight Studio',
    workshopHelp: 'Edit an encounter and preview it with this same runtime.',
    mainGame: 'Capture',
    snake: 'Snake',
    diagnostics: 'Diagnostics',
    testRecovery: 'Test graphics recovery',
    recoveryUnsupported: 'Graphics recovery testing is unavailable in this browser.',
    recoveryRequested: 'Graphics recovery requested. Resume explicitly after restoration.',
    download: 'Download measurements',
    inspectRaw: 'Inspect raw measurements',
    rawMeasurements: 'Raw measurements JSON',
    rawPage: 'Raw JSON page',
    rawPageHelp:
      'Inspection pauses the sortie. Each page contains up to 262,144 characters; join pages in order for the complete JSON record. Download contains all pages. Resume explicitly to continue.',
    measured: 'Local browser measurements; hardware is not inferred.',
    trialHelp:
      'Independent trial: 30-second warm-up, then 120 seconds (15 minutes for soak). It stops automatically. Keep this tab active; interruptions invalidate the trial. Reload for each trial.',
    trialComplete: 'Trial complete · measurements frozen. Download or inspect the record.',
    renderingLost: 'Graphics were interrupted. The sortie is paused.',
    renderingRestored: 'Graphics restored. Resume when ready.',
    prepareFailed: 'Overflight could not be prepared.',
    retryLoading: 'Try preparing again',
    paused: 'Paused · use Resume',
    nextUpgrade: 'Another upgrade is ready',
    fixture: 'Engineering fixture',
    automatedReview: 'Automated review',
    recordClip: 'Record 20-second battlefield clip',
    downloadClip: 'Download battlefield clip',
    clipLimit:
      'Silent canvas only. HUD and upgrade cards are not recorded; combat may pause during choices. Use browser or system screen recording for the complete interface.',
    clip_idle: 'Recording is optional and excludes the sortie from performance qualification.',
    clip_recording: 'Recording the battlefield for 20 seconds…',
    clip_ready: 'Battlefield clip ready. Open Diagnostics to review or download it.',
    clip_unsupported:
      'Canvas recording is unavailable here. Use browser or system screen recording.',
    clip_failed: 'The clip could not be recorded. Use browser or system screen recording.',
    clip_tooLarge: 'Recording stopped at the 16 MiB limit; the incomplete clip was discarded.',
    reviewBuild_fan: 'Fan build',
    reviewBuild_echo: 'Echo build',
    reviewBuild_systems: 'Systems build',
    'reviewBuild_fan-scanner': 'Fan + scanner · no pulse',
    'reviewBuild_fan-shield': 'Fan + shield · no pulse',
    'reviewBuild_echo-scanner': 'Echo + scanner · no pulse',
    'reviewBuild_echo-shield': 'Echo + shield · no pulse',
    reviewDraftBlocked:
      'Review paused: no offered card fits this build, and no rerolls remain. Retry to begin a new review.',
    reviewHelp:
      'An automated pilot uses ordinary movement and boost inputs. Earned upgrades stay visible for 1.5 seconds before selection. Start and Resume remain manual; this is a build review, not a player playtest.',
    fixtureHelp:
      'This fixed population measures capacity; it does not represent normal encounter pacing.',
    previewReady: 'Studio preview is ready. Press Start to fly.',
    runtimeError: 'The sortie stopped after an error. Retry to prepare a new attempt.',
  },
  uk: {
    yourAirframe: 'Льотний майданчик',
    character: 'Оберіть свій дрон',
    characterLocked:
      'Дрон закріплено за цим вильотом. Інший можна обрати перед початком нового вильоту.',
    characterHint:
      'Ваш вигляд, ваш політ. Поки що всі дрони мають однакове керування та покращення.',
    battlefieldEffects: 'Ефекти поля бою',
    keepRemains: 'Залишати рештки ворогів на полі бою',
    remainsHint:
      'Спільне налаштування з основною грою. Найстаріші сліди поступово прибираються для стабільної швидкодії.',
    retrySaving: 'Повторити збереження',
    sortie: 'Виліт',
    spareAirframes: 'Запасні дрони',
    airframeActive: 'Дрон у польоті',
    levelReached: 'Новий рівень',
    upgradeInstalled: 'Покращення встановлено',
    evolutionInstalled: 'Еволюцію відкрито',
    debrief: 'Звіт про виліт',
    victoryKicker: 'Поле зачищено',
    lossKicker: 'Сигнал втрачено',
    victoryMessage: 'Фінальну ціль знищено. Поле бою зберігає історію вашого польоту.',
    lossMessage: 'Кожен проліт мав значення. Використайте цей досвід у наступному вильоті.',
    upgradesEarned: 'Отримані покращення',
    eliteCleared: 'Еліту здолано',
    finalCleared: 'Фінальний танк знищено',
    evolvedBuild: 'Зброю вдосконалено',
    intactSortie: 'Без втрат дронів',
    boostsUsed: 'Прискорень',
    flightLevel: 'Рівень польоту',
    'reviewBuild_fan-scanner': 'Віяло + сканер · без імпульсу',
    'reviewBuild_fan-shield': 'Віяло + щит · без імпульсу',
    'reviewBuild_echo-scanner': 'Відлуння + сканер · без імпульсу',
    'reviewBuild_echo-shield': 'Відлуння + щит · без імпульсу',
    reviewDraftBlocked:
      'Перегляд призупинено: жодна картка не підходить цьому набору, а спроби заміни вичерпано. Почніть новий перегляд.',
    trialHelp:
      'Окремий замір: 30 секунд прогріву, потім 120 секунд (15 хвилин для тривалого тесту). Завершується автоматично. Тримайте вкладку активною; переривання робить замір недійсним. Перезавантажуйте перед кожним заміром.',
    trialComplete: 'Замір завершено · дані зафіксовано. Завантажте або перегляньте запис.',
    title: 'Проліт',
    preparing: 'Готуємо «Проліт»…',
    briefing:
      'Пролітайте крізь прогалини. Дрон автоматично застосовує заряд під час польоту. Збирайте ресурси, покращуйте спорядження та здолайте фінальний танк.',
    field: 'Сутички',
    installed: 'Встановлені сутички',
    exportEncounter: 'Експорт',
    removeEncounter: 'Вилучити',
    removeLocalEncounter: 'Вилучити локальну копію',
    localEncounterRemoved: 'Локальну копію вилучено. Видання спільноти залишається встановленим.',
    communityEncounterOwner: 'Керування у спільноті',
    communityEncounterRecovery:
      'Збережіть точний пакет відновлення та керуйте виданням у спільноті.',
    encounterRemoved: 'Вилучено зі встановленого списку. Поточний виліт збережено.',
    noInstalled: 'Встановіть пакет «Проліт» у студії, щоб грати тут.',
    libraryFailed: 'Не вдалося завантажити встановлені сутички.',
    startHint:
      'WASD / стрілки · Пробіл — прискорення · Escape — пауза. Контролер використовує збережену спільну схему; без неї — лівий стік / RT / Menu. Для радіопульта потрібне збережене спільне налаштування.',
    help: 'Летіть уздовж краю натовпу, щоб заряд влучав у переслідувачів. Ресурси залишаються на землі. Кожен рівень зупиняє виліт для вибору одного з трьох покращень. Напрям атаки ворога фіксується після попередження — встигніть відійти. Здолайте фінальний танк, щоб завершити виліт.',
    settings: 'Налаштування вильоту',
    language: 'Мова',
    airframes: 'Дрони',
    oneAirframe: 'Один дрон',
    threeAirframes: 'Три дрони · спорядження зберігається',
    slowResume: 'Коротке сповільнення після покращення',
    nextSortie: 'Параметри вильоту застосуються після наступного старту або повтору.',
    textFace: 'Шрифт',
    themeText: 'Шрифт теми',
    plainText: 'Звичайний',
    textSize: 'Розмір тексту',
    standard: 'Звичайний',
    large: 'Великий',
    reduced: 'Менше ефектів',
    volume: 'Загальна гучність',
    muted: 'Без звуку',
    hull: 'Міцність',
    boost: 'Прискорення',
    level: 'Рівень',
    kills: 'Знешкоджено',
    upgrades: 'Оберіть покращення',
    upgradeHint: 'Бій призупинено. Порівняйте дію та оберіть наступне покращення.',
    combatModule: 'Зброя',
    supportModule: 'Підтримка',
    oneTimeUpgrade: 'Разове підсилення',
    pulseCharge: 'Заряд імпульсу від польоту',
    flyToCharge: 'Летіть, щоб зарядити сильніший імпульс',
    current: 'Зараз',
    next: 'Далі',
    evolution: 'Еволюція',
    reroll: 'Нові варіанти',
    rerolls: 'замін залишилося',
    emptySlot: 'Вільне місце',
    ready: 'Готово',
    won: 'Виліт виконано',
    lost: 'Виліт завершено',
    elapsed: 'Час',
    salvage: 'Ресурси',
    build: 'Ваше спорядження',
    resultHint: 'Спробуйте іншу комбінацію на тому самому полі.',
    workshop: 'Студія «Проліт»',
    workshopHelp: 'Редагуйте сутичку й перевіряйте її в цьому самому рушії.',
    mainGame: 'Захоплення',
    snake: 'Змійка',
    diagnostics: 'Діагностика',
    testRecovery: 'Перевірити відновлення графіки',
    recoveryUnsupported: 'Перевірка відновлення графіки недоступна в цьому браузері.',
    recoveryRequested: 'Відновлення графіки запущено. Продовжте гру вручну після відновлення.',
    download: 'Завантажити вимірювання',
    inspectRaw: 'Переглянути сирі вимірювання',
    rawMeasurements: 'Сирі вимірювання JSON',
    rawPage: 'Сторінка сирого JSON',
    rawPageHelp:
      'Перегляд призупиняє виліт. Кожна сторінка містить до 262 144 символів; об’єднайте сторінки за порядком для повного запису JSON. Завантаження містить усі сторінки. Продовжте гру вручну.',
    measured: 'Локальні вимірювання браузера; обладнання не визначається за припущеннями.',
    renderingLost: 'Графіку перервано. Виліт призупинено.',
    renderingRestored: 'Графіку відновлено. Продовжте, коли будете готові.',
    prepareFailed: 'Не вдалося підготувати «Проліт».',
    retryLoading: 'Спробувати підготувати ще раз',
    paused: 'Пауза · натисніть «Продовжити»',
    nextUpgrade: 'Готове ще одне покращення',
    fixture: 'Інженерна перевірка',
    automatedReview: 'Автоматизований перегляд',
    recordClip: 'Записати 20 секунд поля бою',
    downloadClip: 'Завантажити запис поля бою',
    clipLimit:
      'Беззвучний запис лише поля бою. Інтерфейс і картки покращень не записуються; під час вибору бій може зупинятися. Для повного інтерфейсу використайте запис екрана браузером або системою.',
    clip_idle: 'Запис необов’язковий і виключає цей виліт з оцінювання продуктивності.',
    clip_recording: 'Записуємо 20 секунд поля бою…',
    clip_ready: 'Запис поля бою готовий. Відкрийте діагностику для перегляду або завантаження.',
    clip_unsupported:
      'Запис поля бою тут недоступний. Скористайтеся записом екрана браузером або системою.',
    clip_failed: 'Не вдалося записати відео. Скористайтеся записом екрана браузером або системою.',
    clip_tooLarge: 'Запис зупинено на межі 16 МіБ; неповне відео відкинуто.',
    reviewBuild_fan: 'Збірка «Віяло»',
    reviewBuild_echo: 'Збірка «Відлуння»',
    reviewBuild_systems: 'Збірка «Системи»',
    reviewHelp:
      'Автоматичний пілот використовує звичайні команди руху й прискорення. Зароблені покращення видно 1,5 секунди до вибору. Старт і продовження — вручну; це перегляд збірки, а не тест гри людиною.',
    fixtureHelp: 'Фіксована кількість ворогів перевіряє продуктивність, а не звичайний темп бою.',
    previewReady: 'Перегляд студії готовий. Натисніть «Почати».',
    runtimeError: 'Виліт зупинено через помилку. Повторіть, щоб підготувати нову спробу.',
  },
});

export const overflightText = (locale, key) =>
  OVERFLIGHT_COPY[locale === 'uk' ? 'uk' : 'en'][key] ?? key;
export function localizedOverflight(value, locale = 'en') {
  if (value === null || value === undefined) return '';
  return typeof value === 'object' ? (value[locale] ?? value.en ?? '') : String(value);
}
