import { overflightText } from './copy.mjs';

export const OVERFLIGHT_HUNT_COPY = Object.freeze({
  en: {
    title: 'Overflight: Raid',
    preparing: 'Preparing Raid…',
    briefing:
      'Your flight is your weapon. Sweep exposed enemies, flank shields and boost through open armor. Hunt the marked targets to complete the Raid.',
    help: 'Touch exposed infantry to destroy them. Shields protect the front; strike the side or rear. Braced troops and vehicles open after their attack. Boost through open machinery once per pass. Your first successful hit each boost refunds part of its cooldown. Twenty kills store Rush: your next boost activates five seconds of faster recovery and double score. Objectives win the Raid; ordinary packs earn score and optional upgrades.',
    contactExposed: 'OPEN → touch to destroy',
    contactGuarded: 'SHIELD → flank or wait for recovery',
    contactHeavy: 'OPEN ARMOR → boost through',
    fixtureHelp:
      'Controlled Raid workload: an automatic route recycles targets to sustain repeatable contact effects. It measures capacity, not player pacing or enjoyment. Start manually and keep the tab active; opening any menu invalidates the trial. Player records are disabled.',
    field: 'Hunting grounds',
    noInstalled: 'Install a Raid package in Raid Studio to play it here.',
    upgradeHint:
      'Flight mastery earned. Compare the two demonstrations and choose your next approach.',
    combatModule: 'Flight upgrade',
    levelReached: 'Flight mastery',
    won: 'Raid complete',
    lost: 'Raid ended',
    victoryKicker: 'Hunt accomplished',
    victoryMessage:
      'Command target destroyed. Refine your route, chase a longer chain, or try another build.',
    lossMessage: 'Read the formation, find an opening and make your next pass count.',
    resultHint:
      'Fastest clear and highest score are separate records. Same ground, a new approach.',
    workshop: 'Raid Studio',
    workshopHelp:
      'Author targets, interception routes and upgrade choices; preview them in this same native runtime.',
    score: 'Score',
    chain: 'Chain',
    bestChain: 'Best chain',
    damageTaken: 'Hull lost',
    couriersCaught: 'Couriers caught',
    couriersEscaped: 'Couriers escaped',
    armorHits: 'Armor breaks',
    objectives: 'Targets',
    sector: 'Sector',
    rush: 'Rush',
    rushReady: 'RUSH READY · next boost',
    rushActive: 'RUSH ACTIVE',
    sameSeed: 'Retry same ground',
    newSortie: 'New sortie',
    fastestClear: 'Fastest clear',
    highestScore: 'Highest score',
    sessionRecords: 'Session records · saving unavailable',
    savedRecords: 'Local records',
    cleanRaid: 'No hull damage',
    finalCleared: 'Command tank destroyed',
    reviewBuild_sweeper: 'Sweeper build',
    reviewBuild_pursuer: 'Pursuer build',
    reviewBuild_breaker: 'Breaker build',
    reviewBuild_objectives: 'Objective route',
  },
  uk: {
    title: 'Проліт: Наліт',
    preparing: 'Готуємо «Наліт»…',
    briefing:
      'Політ — ваша зброя. Змітайте відкритих ворогів, обходьте щити та прискорюйтесь крізь відкриту броню. Знищіть позначені цілі, щоб завершити наліт.',
    help: 'Доторкніться до відкритої піхоти, щоб знищити її. Щити захищають спереду — атакуйте збоку або ззаду. Укріплені бійці й техніка відкриваються після атаки. Прискорюйтесь крізь відкриту техніку один раз за проліт. Перше влучання під час прискорення частково відновлює його. Двадцять знищень готують натиск: наступне прискорення дає п’ять секунд швидшого відновлення й подвійних очок. Цілі завершують наліт; звичайні групи дають очки та додаткові покращення.',
    contactExposed: 'ВІДКРИТО → торкніться й знищіть',
    contactGuarded: 'ЩИТ → обійдіть або дочекайтесь відкриття',
    contactHeavy: 'ВІДКРИТА БРОНЯ → прискорюйтесь наскрізь',
    fixtureHelp:
      'Контрольоване навантаження «Нальоту»: автоматичний маршрут і повторна поява цілей підтримують сталі ефекти контакту. Перевіряє швидкодію, а не темп чи задоволення від гри. Почніть вручну й залишайте вкладку активною; відкриття меню робить замір недійсним. Рекорди гравця вимкнено.',
    field: 'Місця полювання',
    noInstalled: 'Встановіть пакет «Наліт» у студії, щоб грати тут.',
    upgradeHint:
      'Майстерність польоту зростає. Порівняйте дві демонстрації та оберіть новий підхід.',
    combatModule: 'Покращення польоту',
    levelReached: 'Майстерність польоту',
    won: 'Наліт виконано',
    lost: 'Наліт завершено',
    victoryKicker: 'Полювання завершено',
    victoryMessage:
      'Командну ціль знищено. Вдоскональте маршрут, подовжте серію або випробуйте іншу збірку.',
    lossMessage: 'Прочитайте стрій, знайдіть прогалину й зробіть наступний проліт влучним.',
    resultHint:
      'Найшвидше проходження та найбільше очок — окремі рекорди. Те саме поле, новий підхід.',
    workshop: 'Студія «Наліт»',
    workshopHelp:
      'Створюйте цілі, маршрути перехоплення й покращення та перевіряйте їх у цьому самому рушії.',
    score: 'Очки',
    chain: 'Серія',
    bestChain: 'Найкраща серія',
    damageTaken: 'Втрачена міцність',
    couriersCaught: 'Перехоплено кур’єрів',
    couriersEscaped: 'Кур’єрів утекло',
    armorHits: 'Пробиттів броні',
    objectives: 'Цілі',
    sector: 'Сектор',
    rush: 'Натиск',
    rushReady: 'НАТИСК ГОТОВИЙ · наступний ривок',
    rushActive: 'НАТИСК',
    sameSeed: 'Повторити те саме поле',
    newSortie: 'Новий виліт',
    fastestClear: 'Найшвидше проходження',
    highestScore: 'Найбільше очок',
    sessionRecords: 'Рекорди сесії · збереження недоступне',
    savedRecords: 'Локальні рекорди',
    cleanRaid: 'Без втрати міцності',
    finalCleared: 'Командний танк знищено',
    reviewBuild_sweeper: 'Збірка «Змітання»',
    reviewBuild_pursuer: 'Збірка «Переслідувач»',
    reviewBuild_breaker: 'Збірка «Прорив»',
    reviewBuild_objectives: 'Маршрут по цілях',
  },
});
export const overflightHuntText = (locale, key) =>
  OVERFLIGHT_HUNT_COPY[locale === 'uk' ? 'uk' : 'en'][key] ?? overflightText(locale, key);
