export const CLASSIC_COPY = {
  en: {
    title: 'SNAKE',
    tag: 'FPV / LINE · CLASSIC ARCADE',
    intro: 'One more catch. One longer snake.',
    home: 'Main game',
    campaigns: 'All campaigns',
    remix: 'Play the capture remix',
    mode: 'Play mode',
    solo: 'Solo',
    versus: 'Versus',
    team: 'Team',
    language: 'Language',
    chapter: 'Campaign',
    mission: 'Level',
    pace: 'Speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    start: 'Start game',
    resume: 'Resume',
    pause: 'Pause',
    restart: 'Restart',
    next: 'Next level',
    ready: 'READY TO GROW?',
    paused: 'PAUSED',
    won: 'CIRCUIT COMPLETE',
    lost: 'GAME OVER',
    readyHelp:
      'Catch the humanoid. Grow one segment. Keep moving without hitting a wall or your body.',
    controls: 'Arrow keys or WASD to turn · Space / P to pause · swipe or tap the direction pad',
    twoControls: 'P1: WASD · P2: Arrow keys · Space / P to pause · each pad controls its own snake',
    controlsTitle: 'A tap makes a turn',
    controlsHelp:
      'Your snake keeps moving. Direct reversals are ignored. Queue up to two turns. Losing focus pauses the game.',
    caught: 'CAUGHT',
    length: 'LENGTH',
    score: 'SCORE',
    best: 'BEST',
    walls: 'WALLS',
    wrap: 'WRAP EDGES',
    stationary: 'Stationary targets',
    fleeing: 'Fleeing targets',
    noCapture:
      'Classic rules: contact catches only. No territory capture, safe edges or extra lives.',
    teamHelp:
      'Two snakes, one catch goal. Avoid both bodies. Either snake crashing ends the shared round.',
    vsHelp:
      'Matched boards and seed. First to the goal wins; if one crashes, the surviving player wins. Same-time ties are a draw.',
    p1: 'Player 1',
    p2: 'Player 2',
    draw: 'DRAW',
    winner: 'Player {player} wins',
    effects: 'Catch effects',
    brutal: 'Brutal destruction',
    blood: 'Blood and body parts',
    remains: 'Show enemy remains',
    reduced: 'Reduced effects',
    effectHelp: 'Clean by default. Effects never change catches or collisions.',
    up: 'Up',
    down: 'Down',
    left: 'Left',
    right: 'Right',
    changeHelp: 'Mode, level or speed changes prepare a new round. Press Start when ready.',
    session: 'Your round',
    save: 'Save replay',
    load: 'Load replay / saved round',
    continue: 'Continue saved round',
    saved: 'Round saved on this device.',
    storage: 'Local saving is unavailable. You can still export your replay.',
    invalid: 'This file is not a supported Snake round. Your current round was kept.',
    loaded: 'Round restored and paused. Press Resume when ready.',
    wallCrash: 'The head hit a wall. Plan the next corner before you reach it.',
    bodyCrash: 'The head hit a snake body. Leave room for your next loop.',
    winHelp: 'Every target caught. Try the next route or beat your record.',
    limit: 'Round limit reached. Save this replay and start a fresh round.',
    target: 'NEXT CATCH',
    step: 'Move every {ms} ms',
    loading: 'Preparing classic Snake…',
    retry: 'Reload',
    error: 'Snake could not load. Reload, or return to the main game.',
  },
  uk: {
    title: 'ЗМІЙКА',
    tag: 'FPV / LINE · КЛАСИЧНА АРКАДА',
    intro: 'Ще одна ціль. Ще довша змійка.',
    home: 'Головна гра',
    campaigns: 'Усі кампанії',
    remix: 'Ремікс із захопленням території',
    mode: 'Режим гри',
    solo: 'Соло',
    versus: 'Поєдинок',
    team: 'Команда',
    language: 'Мова',
    chapter: 'Кампанія',
    mission: 'Рівень',
    pace: 'Швидкість',
    slow: 'Повільна',
    normal: 'Звичайна',
    fast: 'Швидка',
    start: 'Почати гру',
    resume: 'Продовжити',
    pause: 'Пауза',
    restart: 'Перезапуск',
    next: 'Наступний рівень',
    ready: 'ГОТОВІ РОСТИ?',
    paused: 'ПАУЗА',
    won: 'МАРШРУТ ПРОЙДЕНО',
    lost: 'ГРУ ЗАВЕРШЕНО',
    readyHelp:
      'Спіймайте гуманоїда й виростіть на один сегмент. Рухайтесь, не торкаючись стін чи власного тіла.',
    controls:
      'Стрілки або WASD — поворот · Пробіл / P — пауза · проведіть пальцем або натисніть напрямок',
    twoControls: 'Г1: WASD · Г2: стрілки · Пробіл / P — пауза · кожна панель керує своєю змійкою',
    controlsTitle: 'Один дотик — один поворот',
    controlsHelp:
      'Змійка рухається безперервно. Зворотний напрямок ігнорується. Можна запланувати два повороти. Втрата фокуса ставить гру на паузу.',
    caught: 'СПІЙМАНО',
    length: 'ДОВЖИНА',
    score: 'БАЛИ',
    best: 'РЕКОРД',
    walls: 'СТІНИ',
    wrap: 'ПЕРЕХІД КРІЗЬ КРАЇ',
    stationary: 'Нерухомі цілі',
    fleeing: 'Цілі-втікачі',
    noCapture:
      'Класичні правила: лише дотики. Без захоплення території, безпечних країв і додаткових життів.',
    teamHelp:
      'Дві змійки, спільна мета. Уникайте обох тіл. Зіткнення будь-якої змійки завершує спільний раунд.',
    vsHelp:
      'Однакові поля й початкові умови. Перемагає перший, хто спіймає всі цілі, або той, хто не зіткнувся. Одночасний результат — нічия.',
    p1: 'Гравець 1',
    p2: 'Гравець 2',
    draw: 'НІЧИЯ',
    winner: 'Перемагає гравець {player}',
    effects: 'Ефекти дотику',
    brutal: 'Жорстоке знищення',
    blood: 'Кров і частини тіла',
    remains: 'Показувати рештки ворогів',
    reduced: 'Зменшені ефекти',
    effectHelp: 'За замовчуванням без крові. Ефекти не змінюють дотиків чи зіткнень.',
    up: 'Угору',
    down: 'Униз',
    left: 'Ліворуч',
    right: 'Праворуч',
    changeHelp:
      'Зміна режиму, рівня чи швидкості готує новий раунд. Натисніть «Почати гру», коли будете готові.',
    session: 'Ваш раунд',
    save: 'Зберегти повтор',
    load: 'Завантажити повтор / раунд',
    continue: 'Продовжити збережений раунд',
    saved: 'Раунд збережено на цьому пристрої.',
    storage: 'Локальне збереження недоступне. Ви можете експортувати повтор.',
    invalid: 'Цей файл не є підтримуваним раундом Змійки. Поточну гру збережено.',
    loaded: 'Раунд відновлено й призупинено. Натисніть «Продовжити».',
    wallCrash: 'Голова торкнулася стіни. Плануйте поворот заздалегідь.',
    bodyCrash: 'Голова торкнулася тіла змійки. Залишайте місце для наступної петлі.',
    winHelp: 'Усі цілі спіймано. Спробуйте наступний маршрут або поліпшіть рекорд.',
    limit: 'Досягнуто межі раунду. Збережіть повтор і почніть новий раунд.',
    target: 'НАСТУПНА ЦІЛЬ',
    step: 'Крок кожні {ms} мс',
    loading: 'Підготовка класичної Змійки…',
    retry: 'Оновити',
    error: 'Не вдалося завантажити Змійку. Оновіть сторінку або поверніться до головної гри.',
  },
};
