export const CLASSIC_COPY = {
  en: {
    title: 'SNAKE',
    displaySettings: 'Display & appearance',
    soundSettings: 'Sound & reactions',
    preyDetails: 'Targets, supplies and shutters',
    studio: 'Snake Studio',
    tag: 'FPV / LINE · CLASSIC ARCADE',
    intro: 'Fly. Intercept. Leave room for your cable.',
    format: 'Activity',
    campaign: 'Campaign',
    endless: 'Endless',
    targetRules: 'Target rules',
    authored: 'As designed',
    moving: 'Moving-target remix',
    varied: 'Varied prey',
    remixDescription:
      'This board uses the selected target remix. The accepted roster and objective are shown above; the field guide explains each target.',
    boardAppearance: 'Board appearance',
    'living-circuit': 'Living Circuit',
    boardScene: 'Living Circuit scene',
    auto: 'Auto · by chapter',
    orchard: 'Orchard Workshop',
    workshop: 'Workshop',
    relay: 'Field Relay',
    signalClear: 'Clear reception',
    signalWarning: 'Signal warning · plan ahead',
    signalJammed: 'Interference · enemies hidden',
    signalStable: 'Pulse · clear reception',
    signalLocalHelp:
      'Enemies keep moving unseen. Catch the jammer at its antenna beacon, leave its range, or use Pulse.',
    signalBroadcastHelp:
      'Enemies keep moving unseen across the board. Catch the jammer at its double antenna beacon or use Pulse.',
    variableSignalRecord:
      '★ Verified completion · bursts change each attempt. Personal records use variable conditions.',
    theme: 'Game theme',
    retro: 'Retro Field',
    castLabel: 'Character cast',
    campaignCast: 'Campaign cast',
    rivals: 'Rival crews',
    fieldGuide: 'Enemy field guide · pauses play',
    reactions: 'Character reactions and dialogue',
    specialistHelp:
      'Catch only an exposed side or recovery state. Protected contact ends the attempt. Keep clear of walls and cable.',
    encounterSummary: '{actors} · Up to {count} active · {objective}',
    catchQuota: 'Catch {goal}',
    specialistNotice:
      'Specialist challenge: protected contact is dangerous. Open the field guide before flying.',
    shieldCrash: 'You hit the protected front of a shield. Approach from the side or behind.',
    armorCrash:
      'The armor was closed. Wait for the open recovery; Pulse holds the current armor state.',
    specialistCrash: 'Protected contact is dangerous. Watch the target’s vulnerable opening.',
    preset: 'Endless rules',
    classic: 'Classic',
    pursuit: 'Pursuit',
    tactical: 'Tactical',
    arcade: 'Arcade',
    duel: 'Versus format',
    scoreDuel: 'Score duel · 3 min',
    survival: 'Survival duel',
    featured: 'Featured sortie',
    newRoute: 'New route',
    appearance: 'Flight trail',
    cable: 'Cable',
    signal: 'Signal',
    steering: 'Touch steering',
    turns: 'Turn left / right',
    dpad: 'Direction pad',
    turnLeft: 'Turn left',
    turnRight: 'Turn right',
    review: 'Watch final 8 moves',
    slowOffer: 'Try Slow pace',
    accent: 'Chapter accent',
    defaultAccent: 'Blue / yellow',
    muted: 'Mute sound',
    volume: 'Master volume',
    effectsVolume: 'Effects volume',
    clock: 'TIME',
    queued: 'NEXT TURN',
    progress: '{done} / {chapterTotal} cleared · {all} / {total} total',
    lastPlayed: 'Last played: {name}',
    nextUncleared: 'Next uncleared: {name}',
    recordDetail: 'Best score {score} · Fastest {time} · Fewest moves {moves}',
    noRecord: 'Clear this route to record your time and movement record.',
    noEndlessRecord: 'Fly this route to set your Endless score record.',
    seconds: '{value}s',
    setupLabel: 'Game setup',
    rulesLabel: 'Round rules',
    progressLabel: 'Campaign progress',
    arenaLabel: 'Snake game',
    seed: 'Route {seed}',
    modernTargets: 'Patrols, runners and sprinters',
    scoreHelp: 'Three minutes. A crashed board stops; the other keeps flying. Highest score wins.',
    survivalHelp:
      'Catch within 30 seconds. Last pilot flying wins. At three minutes, compare catches. Empty field, no supplies.',
    endlessHelp:
      'Keep catching until collision or a full board. Your cable is the growing challenge.',
    teamwork: 'Both pilots contributed',
    noSupplies: 'Cleared without supplies',
    reviewPlaying: 'Final moves · replay only',
    chapter: 'Chapter',
    home: 'Main game',
    campaigns: 'All campaigns',
    remix: 'Play the capture remix',
    mode: 'Play mode',
    solo: 'Solo',
    versus: 'Versus',
    team: 'Team',
    language: 'Language',
    mission: 'Level',
    pace: 'Speed',
    slow: 'Slow',
    normal: 'Normal',
    fast: 'Fast',
    start: 'Start mission',
    resume: 'Resume',
    pause: 'Pause',
    restart: 'Restart',
    next: 'Next level',
    ready: 'READY FOR LAUNCH',
    paused: 'PAUSED',
    won: 'CIRCUIT COMPLETE',
    lost: 'GAME OVER',
    readyHelp:
      'Catch the humanoid. Grow one segment. Keep moving without hitting a wall or your body.',
    controls: 'Arrows / WASD to fly · Esc / P to pause · R to retry after a crash',
    twoControls: 'P1: WASD · P2: Arrow keys · Esc / P to pause · each pad controls its own snake',
    controlsTitle: 'A tap makes a turn',
    controlsHelp:
      'Your drone keeps moving. Direct reversals are ignored. Queue up to two turns. Losing focus pauses the game. Each Team pilot uses their own buttons or controller.',
    preyLegend:
      'Patrol pack: patroller. Light webbing: runner. Headset and crouched stance: sprinter—watch its warning and rest. Satchel: optional courier, +250 points and extra cable. Pulse holds prey; Reel shortens your cable. Supplies activate on contact. Shutters warn before closing and wait for an occupied cable.',
    caught: 'CAUGHT',
    length: 'LENGTH',
    score: 'SCORE',
    best: 'DEVICE BEST',
    walls: 'WALLS',
    wrap: 'WRAP EDGES',
    stationary: 'Stationary targets',
    fleeing: 'Fleeing targets',
    noCapture:
      'Classic rules: contact catches only. No territory capture, safe edges or extra lives.',
    teamHelp:
      'Two snakes, one catch goal. Avoid both bodies. Either snake crashing ends the shared round.',
    vsHelp:
      'Matched boards and seed. First to the goal wins; if one crashes, the surviving player wins. Same-time ties are a draw.',
    p1: 'Player 1',
    p2: 'Player 2',
    draw: 'DRAW',
    winner: 'Player {player} wins',
    effects: 'Catch effects',
    brutal: 'Brutal destruction',
    blood: 'Blood and body parts',
    remains: 'Show enemy remains',
    reduced: 'Reduced effects',
    effectHelp: 'Clean by default. Effects never change catches or collisions.',
    up: 'Up',
    down: 'Down',
    left: 'Left',
    right: 'Right',
    changeHelp: 'Mode, level or speed changes prepare a new round. Press Start when ready.',
    session: 'Your round',
    save: 'Save replay',
    load: 'Load replay / saved round',
    continue: 'Continue saved round',
    saved: 'Round saved on this device.',
    storage: 'Local saving is unavailable. You can still export your replay.',
    invalid: 'This file is not a supported Snake round. Your current round was kept.',
    loaded: 'Round restored and paused. Press Resume when ready.',
    loadedComplete: 'Completed round restored. Retry or choose the next level.',
    wallCrash: 'The head hit a wall. Plan the next corner before you reach it.',
    bodyCrash: 'The head hit a snake body. Leave room for your next loop.',
    partnerCrash: 'You hit your partner’s cable. Keep a separate return route.',
    headCrash: 'The drones collided. Choose different crossing times.',
    catchDeadline: 'No catch within 30 seconds. Intercept the next target sooner.',
    otherPilotFlying: 'The other pilot is still flying.',
    winHelp: 'Every target caught. Try the next route or beat your record.',
    limit: 'Round limit reached. Save this replay and start a fresh round.',
    target: 'NEXT CATCH',
    step: 'Move every {ms} ms',
    loading: 'Preparing classic Snake…',
    retry: 'Reload',
    error: 'Snake could not load. Reload, or return to the main game.',
  },
  uk: {
    'living-circuit': 'Живий контур',
    boardScene: 'Сцена «Живого контуру»',
    auto: 'Авто · за розділом',
    orchard: 'Майстерня в саду',
    workshop: 'Майстерня',
    relay: 'Польовий ретранслятор',
    signalClear: 'Чистий прийом',
    signalWarning: 'Увага: сплануйте маршрут',
    signalJammed: 'Перешкоди · вороги приховані',
    signalStable: 'Імпульс · чистий прийом',
    signalLocalHelp:
      'Невидимі вороги продовжують рух. Спіймайте глушник біля маячка антени, вийдіть із його зони або застосуйте Імпульс.',
    signalBroadcastHelp:
      'Невидимі вороги рухаються по всьому полю. Спіймайте глушник біля подвійного маячка антени або застосуйте Імпульс.',
    variableSignalRecord:
      '★ Перевірене завершення · спалахи змінюються щоразу. Особисті рекорди за змінних умов.',
    title: 'ЗМІЙКА',
    displaySettings: 'Екран і вигляд',
    soundSettings: 'Звук і реакції',
    preyDetails: 'Цілі, припаси та заслінки',
    studio: 'Студія Змійки',
    tag: 'FPV / LINE · КЛАСИЧНА АРКАДА',
    intro: 'Лети. Перехоплюй. Залиш місце для кабелю.',
    format: 'Гра',
    campaign: 'Кампанія',
    endless: 'Без кінця',
    targetRules: 'Правила цілей',
    authored: 'Як задумано',
    moving: 'Ремікс із рухливими цілями',
    varied: 'Різноманітні цілі',
    remixDescription:
      'Це поле використовує обраний ремікс цілей. Прийнятий склад і мету показано вище; довідник пояснює кожну ціль.',
    boardAppearance: 'Вигляд поля',
    theme: 'Тема гри',
    retro: 'Ретрополе',
    castLabel: 'Стиль персонажів',
    campaignCast: 'Стиль кампанії',
    rivals: 'Команди суперників',
    fieldGuide: 'Довідник ворогів · призупиняє гру',
    reactions: 'Реакції та голоси персонажів',
    specialistHelp:
      'Ловіть лише з відкритого боку або під час відновлення. Дотик до захисту завершує спробу. Уникайте стін і кабелю.',
    encounterSummary: '{actors} · До {count} активних · {objective}',
    catchQuota: 'Перехопіть {goal}',
    specialistNotice:
      'Особливе випробування: захищений контакт небезпечний. Перед польотом відкрийте довідник.',
    shieldCrash: 'Ви влучили в захищений фронт щита. Підходьте збоку або ззаду.',
    armorCrash:
      'Броня була закрита. Дочекайтеся відкритого відпочинку; Імпульс утримує поточний стан броні.',
    specialistCrash: 'Захищений контакт небезпечний. Стежте за відкритим станом цілі.',
    preset: 'Правила нескінченної гри',
    classic: 'Класика',
    pursuit: 'Переслідування',
    tactical: 'Тактика',
    arcade: 'Аркада',
    duel: 'Формат поєдинку',
    scoreDuel: 'Бали · 3 хв',
    survival: 'На виживання',
    featured: 'Особливий виліт',
    newRoute: 'Новий маршрут',
    appearance: 'Слід польоту',
    cable: 'Кабель',
    signal: 'Сигнал',
    steering: 'Сенсорне керування',
    turns: 'Поворот ліворуч / праворуч',
    dpad: 'Панель напрямків',
    turnLeft: 'Поворот ліворуч',
    turnRight: 'Поворот праворуч',
    review: 'Останні 8 кроків',
    slowOffer: 'Спробувати повільніше',
    accent: 'Барви розділу',
    defaultAccent: 'Синій / жовтий',
    muted: 'Вимкнути звук',
    volume: 'Загальна гучність',
    effectsVolume: 'Гучність ефектів',
    clock: 'ЧАС',
    queued: 'НАСТУПНИЙ ПОВОРОТ',
    progress: '{done} / {chapterTotal} пройдено · {all} / {total} загалом',
    lastPlayed: 'Остання гра: {name}',
    nextUncleared: 'Наступний непройдений: {name}',
    recordDetail: 'Рекорд {score} · Найшвидше {time} · Найменше кроків {moves}',
    noRecord: 'Пройдіть маршрут, щоб зберегти рекорди часу та кроків.',
    noEndlessRecord: 'Летіть цим маршрутом і встановіть рекорд нескінченної гри.',
    seconds: '{value}с',
    setupLabel: 'Налаштування гри',
    rulesLabel: 'Правила раунду',
    progressLabel: 'Прогрес кампанії',
    arenaLabel: 'Гра «Змійка»',
    seed: 'Маршрут {seed}',
    modernTargets: 'Патрулі, втікачі та спринтери',
    scoreHelp:
      'Три хвилини. Після зіткнення поле зупиняється, суперник летить далі. Перемагає найбільша сума балів.',
    survivalHelp:
      'Ловіть ціль за 30 секунд. Перемагає той, хто залишився. Через три хвилини порівнюються дотики. Порожнє поле без припасів.',
    endlessHelp: 'Ловіть до зіткнення або заповнення поля. Кабель стає дедалі довшим.',
    teamwork: 'Обидва пілоти зробили внесок',
    noSupplies: 'Пройдено без припасів',
    reviewPlaying: 'Останні кроки · лише повтор',
    chapter: 'Розділ',
    home: 'Головна гра',
    campaigns: 'Усі кампанії',
    remix: 'Ремікс із захопленням території',
    mode: 'Режим гри',
    solo: 'Соло',
    versus: 'Поєдинок',
    team: 'Команда',
    language: 'Мова',
    mission: 'Рівень',
    pace: 'Швидкість',
    slow: 'Повільна',
    normal: 'Звичайна',
    fast: 'Швидка',
    start: 'Почати місію',
    resume: 'Продовжити',
    pause: 'Пауза',
    restart: 'Перезапуск',
    next: 'Наступний рівень',
    ready: 'ГОТОВІ ДО СТАРТУ',
    paused: 'ПАУЗА',
    won: 'МАРШРУТ ПРОЙДЕНО',
    lost: 'ГРУ ЗАВЕРШЕНО',
    readyHelp:
      'Спіймайте гуманоїда й виростіть на один сегмент. Рухайтесь, не торкаючись стін чи власного тіла.',
    controls: 'Стрілки / WASD або кнопки повороту · Esc / P — пауза · R — повтор після зіткнення',
    twoControls: 'Г1: WASD · Г2: стрілки · Esc / P — пауза · кожна панель керує своєю змійкою',
    controlsTitle: 'Один дотик — один поворот',
    controlsHelp:
      'Дрон рухається безперервно. Зворотний напрямок ігнорується. Можна запланувати два повороти. Втрата фокуса ставить гру на паузу. Кожен пілот команди має власні кнопки або контролер.',
    preyLegend:
      'Патрульний рюкзак — патруль. Легке спорядження — бігун. Гарнітура й присідання — спринтер: стежте за попередженням і відпочинком. Сумка — необов’язковий кур’єр: +250 балів і сегмент кабелю. Імпульс зупиняє цілі, котушка скорочує кабель. Припаси діють від дотику. Заслінки попереджають перед закриттям і чекають, доки кабель звільнить прохід.',
    caught: 'СПІЙМАНО',
    length: 'ДОВЖИНА',
    score: 'БАЛИ',
    best: 'РЕКОРД ПРИСТРОЮ',
    walls: 'СТІНИ',
    wrap: 'ПЕРЕХІД КРІЗЬ КРАЇ',
    stationary: 'Нерухомі цілі',
    fleeing: 'Цілі-втікачі',
    noCapture:
      'Класичні правила: лише дотики. Без захоплення території, безпечних країв і додаткових життів.',
    teamHelp:
      'Дві змійки, спільна мета. Уникайте обох тіл. Зіткнення будь-якої змійки завершує спільний раунд.',
    vsHelp:
      'Однакові поля й початкові умови. Перемагає перший, хто спіймає всі цілі, або той, хто не зіткнувся. Одночасний результат — нічия.',
    p1: 'Гравець 1',
    p2: 'Гравець 2',
    draw: 'НІЧИЯ',
    winner: 'Перемагає гравець {player}',
    effects: 'Ефекти дотику',
    brutal: 'Жорстоке знищення',
    blood: 'Кров і частини тіла',
    remains: 'Показувати рештки ворогів',
    reduced: 'Зменшені ефекти',
    effectHelp: 'За замовчуванням без крові. Ефекти не змінюють дотиків чи зіткнень.',
    up: 'Угору',
    down: 'Униз',
    left: 'Ліворуч',
    right: 'Праворуч',
    changeHelp:
      'Зміна режиму, рівня чи швидкості готує новий раунд. Натисніть «Почати гру», коли будете готові.',
    session: 'Ваш раунд',
    save: 'Зберегти повтор',
    load: 'Завантажити повтор / раунд',
    continue: 'Продовжити збережений раунд',
    saved: 'Раунд збережено на цьому пристрої.',
    storage: 'Локальне збереження недоступне. Ви можете експортувати повтор.',
    invalid: 'Цей файл не є підтримуваним раундом Змійки. Поточну гру збережено.',
    loaded: 'Раунд відновлено й призупинено. Натисніть «Продовжити».',
    loadedComplete: 'Завершений раунд відновлено. Повторіть або оберіть наступний рівень.',
    wallCrash: 'Голова торкнулася стіни. Плануйте поворот заздалегідь.',
    bodyCrash: 'Голова торкнулася тіла змійки. Залишайте місце для наступної петлі.',
    partnerCrash: 'Зіткнення з кабелем напарника. Залишайте окремий шлях повернення.',
    headCrash: 'Дрони зіткнулися. Проходьте перехрестя в різний час.',
    catchDeadline: 'Жодної цілі за 30 секунд. Перехопіть наступну раніше.',
    otherPilotFlying: 'Інший пілот продовжує політ.',
    winHelp: 'Усі цілі спіймано. Спробуйте наступний маршрут або поліпшіть рекорд.',
    limit: 'Досягнуто межі раунду. Збережіть повтор і почніть новий раунд.',
    target: 'НАСТУПНА ЦІЛЬ',
    step: 'Крок кожні {ms} мс',
    loading: 'Підготовка класичної Змійки…',
    retry: 'Оновити',
    error: 'Не вдалося завантажити Змійку. Оновіть сторінку або поверніться до головної гри.',
  },
};
