import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { parse as parseJS } from 'acorn';
import { parse as parseHTML } from 'parse5';
import { extractContent } from './localization-content.mjs';
import { auditSources } from './localization-audit.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const locales = ['en', 'uk'];
export async function readCatalogs(directory = root) {
  const resources = {};
  for (const locale of locales) {
    resources[locale] = {};
    for (const file of (await fs.readdir(path.join(directory, 'game/locales', locale))).sort()) {
      if (!file.endsWith('.json')) continue;
      resources[locale][file.slice(0, -5)] = JSON.parse(
        await fs.readFile(path.join(directory, 'game/locales', locale, file), 'utf8'),
      );
    }
  }
  return resources;
}
export function catalogBundle(resources) {
  // Store semantic keys once across locales. Ukrainian-only plural forms retain
  // their own cells; a missing value is never turned into an English fallback.
  // Front-code sorted message values to share repeated text and prefixes. This
  // is only a lossless distribution encoding: translators still edit complete
  // sentences, and i18next receives the original strings synchronously.
  const strings = [
    ...new Set(
      locales.flatMap((locale) =>
        Object.values(resources[locale]).flatMap((namespace) => Object.values(namespace)),
      ),
    ),
  ].sort();
  const stringIds = new Map(strings.map((value, index) => [value, index]));
  let previous = '';
  const prefixes = strings.map((value) => {
    let length = 0;
    while (length < previous.length && length < value.length && previous[length] === value[length])
      length++;
    const encoded = [length, value.slice(length)];
    previous = value;
    return encoded;
  });
  const tables = Object.fromEntries(
    [...new Set(locales.flatMap((locale) => Object.keys(resources[locale])))].map((namespace) => [
      namespace,
      [
        ...new Set(locales.flatMap((locale) => Object.keys(resources[locale][namespace] || {}))),
      ].map((key) => [
        key,
        ...locales.map((locale) => stringIds.get(resources[locale][namespace]?.[key]) ?? null),
      ]),
    ]),
  );
  return (
    '// Generated by npm run i18n:build. Edit game/locales instead.\n' +
    '(() => {\nconst resources = {en: {}, uk: {}};\nconst locales = ["en", "uk"];\n' +
    `const prefixes = ${JSON.stringify(prefixes).replaceAll('<', '\\u003c')};\n` +
    'let previous = "";\nconst strings = prefixes.map(([length, suffix]) => (previous = previous.slice(0, length) + suffix));\n' +
    `const tables = ${JSON.stringify(tables).replaceAll('<', '\\u003c')};\n` +
    'for (const [namespace, rows] of Object.entries(tables)) {\n' +
    '  locales.forEach((locale, index) => {\n' +
    '    resources[locale][namespace] = Object.fromEntries(rows.filter(row => row[index + 1] !== null).map(row => [row[0], strings[row[index + 1]]]));\n' +
    '  });\n}\nglobalThis.RevealLineTranslations = resources;\n})();\n'
  );
}
export async function contentBundle(directory = root, resources) {
  const byText = new Map(
    Object.entries(resources.en.content).map(([key, value]) => [value, `content:${key}`]),
  );
  const registry = await extractContent(directory, (text, source) => {
    const key = byText.get(text);
    if (!key) throw new Error(`Uncatalogued content: ${source.file}${source.pointer}: ${text}`);
    return key;
  });
  return compactContentRegistry(registry);
}
/** Source locations stay in extraction reports. Runtime records share exact
 * field definitions across compiled difficulties and navigation projections. */
export function compactContentRegistry(registry) {
  const messages = [];
  const messageIds = new Map();
  const groups = [];
  const groupIds = new Map();
  const records = [];
  for (const [identity, { fields }] of Object.entries(registry)) {
    const entries = Object.entries(fields).map(([field, message]) => {
      const serialized = JSON.stringify(message);
      if (!messageIds.has(serialized)) {
        messageIds.set(serialized, messages.length);
        messages.push(message);
      }
      return [field, messageIds.get(serialized)];
    });
    const serialized = JSON.stringify(entries);
    if (!groupIds.has(serialized)) {
      groupIds.set(serialized, groups.length);
      groups.push(entries);
    }
    records.push([identity, groupIds.get(serialized)]);
  }
  return (
    '// Generated from explicitly registered first-party content.\n' +
    `const messages = ${JSON.stringify(messages)};\n` +
    `const groups = ${JSON.stringify(groups)}.map(entries => ({fields: Object.fromEntries(entries.map(([field, index]) => [field, messages[index]]))}));\n` +
    `export default Object.fromEntries(${JSON.stringify(records)}.map(([identity, index]) => [identity, groups[index]]));\n`
  );
}
async function sourceFiles(directory = root) {
  const output = [];
  const walk = async (relative) => {
    for (const entry of await fs.readdir(path.join(directory, relative), { withFileTypes: true })) {
      const file = path.posix.join(relative, entry.name);
      if (
        [
          'vendor',
          'i18n',
          'locales',
          'library',
          'test',
          'node_modules',
          'assets',
          'fonts',
          'art',
        ].includes(entry.name)
      )
        continue;
      if (entry.isDirectory()) await walk(file);
      else if (/\.(mjs|js|html)$/.test(entry.name) && !/\.test\.|\/test-/.test(file))
        output.push(file);
    }
  };
  for (const dir of ['game', 'site', 'authoring']) await walk(dir);
  for (const file of [
    'scripts/game-cli.mjs',
    'scripts/pages-current-entry.mjs',
    'scripts/release-catalog.mjs',
  ]) {
    try {
      await fs.access(path.join(directory, file));
      output.push(file);
    } catch {
      /* Small build fixtures may omit public pages. */
    }
  }
  return output.sort();
}
export async function extractTranslations(directory = root) {
  const references = new Map();
  const add = (key, file, line) => {
    if (typeof key !== 'string' || !key.includes(':')) return;
    if (!references.has(key)) references.set(key, []);
    references.get(key).push({ file, line });
  };
  for (const file of await sourceFiles(directory)) {
    const source = await fs.readFile(path.join(directory, file), 'utf8');
    if (file.endsWith('.html')) {
      const walk = (node) => {
        for (const attribute of node.attrs || [])
          if (
            /^data-i18n(?:$|-(?:rich|aria-label|title|placeholder|alt|content|data-menu-label)$)/.test(
              attribute.name,
            )
          )
            add(attribute.value, file, node.sourceCodeLocation?.startLine);
        node.childNodes?.forEach(walk);
      };
      walk(parseHTML(source, { sourceCodeLocationInfo: true }));
    } else {
      const walk = (node) => {
        if (!node || typeof node !== 'object') return;
        if (node.type === 'CallExpression' && ['t', 'localizedMessage'].includes(node.callee?.name))
          add(node.arguments[0]?.value, file, node.loc.start.line);
        // Explicit key registries keep compatibility adapters visible to validation.
        if (
          node.type === 'Literal' &&
          typeof node.value === 'string' &&
          /^(?:common|interface|gameplay|content|tools|website|errors):[\w.]+$/.test(node.value)
        )
          add(node.value, file, node.loc.start.line);
        const markup =
          node.type === 'TemplateElement'
            ? node.value.cooked
            : node.type === 'Literal' && typeof node.value === 'string'
              ? node.value
              : '';
        for (const match of (markup || '').matchAll(
          /data-i18n(?:-(?:rich|aria-label|title|placeholder|alt|content|data-menu-label))?=["']([^"']+)["']/g,
        ))
          add(match[1], file, node.loc.start.line);
        for (const value of Object.values(node))
          if (Array.isArray(value)) value.forEach(walk);
          else if (value && typeof value === 'object') walk(value);
      };
      walk(parseJS(source, { ecmaVersion: 'latest', sourceType: 'module', locations: true }));
    }
  }
  return Object.fromEntries([...references].sort(([a], [b]) => a.localeCompare(b)));
}
const placeholders = (text) =>
  [...text.matchAll(/\{\{\s*([^}]+?)\s*\}\}|\[\[([^\]]+)\]\]/g)]
    .map((match) => match[1] || match[2])
    .sort()
    .join('|');
export function validateCatalogMessages(resources) {
  const errors = [];
  for (const [namespace, entries] of Object.entries(resources.en)) {
    for (const [key, english] of Object.entries(entries)) {
      const ukrainian = resources.uk[namespace]?.[key];
      if (typeof ukrainian !== 'string' || !ukrainian.trim())
        errors.push(`Missing Ukrainian: ${namespace}:${key}`);
      else if (placeholders(english) !== placeholders(ukrainian))
        errors.push(`Interpolation mismatch: ${namespace}:${key}`);
      if (key.endsWith('_one')) {
        const stem = key.slice(0, -4);
        for (const form of ['one', 'few', 'many', 'other'])
          if (!resources.uk[namespace]?.[`${stem}_${form}`])
            errors.push(`Missing Ukrainian plural: ${namespace}:${stem}_${form}`);
      }
    }
  }
  for (const [namespace, entries] of Object.entries(resources.uk)) {
    for (const [key, ukrainian] of Object.entries(entries)) {
      if (resources.en[namespace]?.[key] !== undefined) continue;
      const other = key.replace(/_(?:one|few|many|other)$/, '_other');
      const english = resources.en[namespace]?.[other];
      if (other === key || english === undefined)
        errors.push(`Missing English: ${namespace}:${key}`);
      else if (typeof ukrainian !== 'string' || !ukrainian.trim())
        errors.push(`Missing Ukrainian: ${namespace}:${key}`);
      else if (placeholders(english) !== placeholders(ukrainian))
        errors.push(`Interpolation mismatch: ${namespace}:${key}`);
    }
  }
  return errors;
}
export async function validateLocalization(directory = root, { checkBundle = true } = {}) {
  const resources = await readCatalogs(directory);
  const references = await extractTranslations(directory);
  const errors = validateCatalogMessages(resources);
  for (const key of Object.keys(references)) {
    const [namespace, name] = key.split(':');
    if (!resources.en[namespace]?.[name] && !resources.en[namespace]?.[`${name}_other`])
      errors.push(`Uncatalogued key: ${key}`);
  }
  if (
    checkBundle &&
    (await fs.readFile(path.join(directory, 'game/i18n/catalogs.mjs'), 'utf8')) !==
      catalogBundle(resources)
  )
    errors.push('Catalog bundle is stale; run npm run i18n:build.');
  if (
    checkBundle &&
    (await fs.readFile(path.join(directory, 'game/i18n/content-registry.mjs'), 'utf8')) !==
      (await contentBundle(directory, resources))
  )
    errors.push('Content registry is stale; run npm run i18n:build.');
  if (errors.length) throw new Error(errors.join('\n'));
  return {
    localization: {
      locales,
      messages: Object.values(resources.en).reduce(
        (sum, entries) => sum + Object.keys(entries).length,
        0,
      ),
      references: Object.keys(references).length,
    },
  };
}
async function main() {
  const command = process.argv[2] || 'check';
  if (command === 'audit') {
    console.log(
      JSON.stringify(await auditSources(root, await sourceFiles(), await readCatalogs()), null, 2),
    );
    return;
  }
  if (command === 'build') {
    const resources = await readCatalogs();
    await fs.writeFile(path.join(root, 'game/i18n/catalogs.mjs'), catalogBundle(resources));
    await fs.writeFile(
      path.join(root, 'game/i18n/content-registry.mjs'),
      await contentBundle(root, resources),
    );
    return;
  }
  if (command === 'extract') {
    const resources = await readCatalogs();
    const groups = new Map();
    for (const [ns, entries] of Object.entries(resources.en))
      for (const [key, value] of Object.entries(entries)) {
        const group = groups.get(value) || [];
        group.push(`${ns}:${key}`);
        groups.set(value, group);
      }
    const content = [];
    const byText = new Map(
      Object.entries(resources.en.content).map(([key, value]) => [value, `content:${key}`]),
    );
    await extractContent(root, (text, source) => {
      content.push({ ...source, key: byText.get(text) || null, text });
      return byText.get(text);
    });
    console.log(
      JSON.stringify(
        {
          references: await extractTranslations(),
          content,
          missingContent: content.filter((item) => !item.key),
          sharedKeyCandidates: [...groups]
            .filter(([, keys]) => keys.length > 1)
            .map(([text, keys]) => ({ text, keys })),
        },
        null,
        2,
      ),
    );
    return;
  }
  console.log(JSON.stringify(await validateLocalization(), null, 2));
}
if (process.argv[1] && import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href)
  await main();
